import type { ArticleRecord } from './articles';

export type HistoricalIssue = { year:number; month:number; title:string; slug:string; domain:string; challenge:string; design:string; failure:string; practice:string; tags:string[]; ata:string[] };

export const historicalIssues: HistoricalIssue[] = [
  {year:2025,month:1,title:'Normalizing Aircraft Health Messages Without Erasing Meaning',slug:'2025-01-aircraft-health-message-normalization',domain:'aircraft health-message integration',challenge:'OEM and fleet sources express similar conditions with different identifiers, severities, timestamps, and configuration assumptions',design:'preserve the source envelope, map through versioned canonical concepts, and expose unresolved semantics instead of coercing them',failure:'a universal schema that looks clean while discarding source-specific diagnostic context',practice:'begin with one fleet and one maintenance decision; reconcile mappings with engineering before expanding',tags:['Health messages','Canonical events','Data contracts'],ata:[]},
  {year:2025,month:2,title:'Prioritizing the Maintenance-Control Queue by Operational Consequence',slug:'2025-02-maintenance-control-prioritization',domain:'maintenance-control prioritization',challenge:'technical urgency, dispatch exposure, station capability, evidence quality, and time-to-decision compete inside one queue',design:'separate consequence, urgency, confidence, and controllability so controllers can inspect why work moved',failure:'one opaque priority score that converts policy choices into false mathematical certainty',practice:'shadow the live queue, compare ranking disagreements, and let controllers correct causal factors',tags:['Maintenance control','Prioritization','Human authority'],ata:[]},
  {year:2025,month:3,title:'Detecting Repeat Defects as Cases, Not Keyword Matches',slug:'2025-03-repeat-defect-case-detection',domain:'repeat-defect detection',challenge:'write-ups vary by language while component position, configuration, corrective action, and recurrence window carry the stronger signal',design:'assemble explainable candidate cases using identity, chronology, symptom concepts, and maintenance outcomes',failure:'declaring recurrence from text similarity without exposure or engineering review',practice:'test against engineer-built cases and publish both missed joins and false joins',tags:['Repeat defects','Case intelligence','Reliability'],ata:[]},
  {year:2025,month:4,title:'Technical Records as a Verifiable Chain of Aircraft Evidence',slug:'2025-04-technical-records-lineage',domain:'technical-record modernization',challenge:'scanned forms, electronic task data, signatures, component transactions, and revisions often lose their relationships during handoff',design:'use immutable document identity, signed events, controlled revisions, and completeness rules around the aircraft record',failure:'digitizing pages without creating traceable state or authoritative ownership',practice:'map one record class from creation through audit and repair every ambiguous handoff',tags:['Technical records','Lineage','Digital evidence'],ata:[]},
  {year:2025,month:5,title:'Forecasting Parts Demand Under Maintenance Uncertainty',slug:'2025-05-parts-demand-forecasting',domain:'maintenance material planning',challenge:'scheduled demand, stochastic removals, fleet changes, repair turn time, pooling, and no-fault-found behavior interact across different horizons',design:'combine causal demand segments with uncertainty bands and scenario decisions rather than one point forecast',failure:'optimizing forecast accuracy while ignoring service level, expedites, and inventory consequence',practice:'start with a rotable family and evaluate decisions under realistic lead-time and removal scenarios',tags:['Parts forecasting','Rotables','Supply chain'],ata:[]},
  {year:2025,month:6,title:'Where Predictive Maintenance Fails—and How to Design Around It',slug:'2025-06-predictive-maintenance-limitations',domain:'predictive-maintenance product design',challenge:'rare failures, censored histories, configuration drift, intervention effects, and weak ground truth make confident predictions fragile',design:'bound the use case, disclose applicability, prefer evidence windows, and build human review plus outcome adjudication',failure:'presenting a model probability as a maintenance instruction or remaining-useful-life fact',practice:'run prospective shadow evaluation and study operational decisions before automating delivery',tags:['Predictive maintenance','Model limits','Evaluation'],ata:[]},
  {year:2025,month:7,title:'Reading APU Performance as an Operating System, Not a Single Trend',slug:'2025-07-apu-performance-monitoring',domain:'APU health monitoring',challenge:'EGT, speed, starts, bleed demand, ambient conditions, control logic, and maintenance actions interact across operating regimes',design:'create regime-aware baselines and an evidence timeline that connects trends to configuration and work history',failure:'using fleet-wide static thresholds that confuse environment and utilization with degradation',practice:'review one APU family with engineering and validate alerts against inspection and shop evidence',tags:['APU health','Trend monitoring','Condition context'],ata:['49']},
  {year:2025,month:8,title:'Landing-Gear Reliability Through Events, Cycles, and Configuration',slug:'2025-08-landing-gear-reliability-analytics',domain:'landing-gear reliability analytics',challenge:'indications, extension events, brake and tire context, hard-landing inspections, component positions, and cyclic exposure live in separate systems',design:'build a cycle-centered event history with component effectivity and clearly bounded engineering indicators',failure:'correlating fleet events without distinguishing position, variant, modification, or operating exposure',practice:'select a specific failure family and reconstruct complete aircraft and component histories',tags:['Landing gear','Reliability analytics','Event history'],ata:['32']},
  {year:2025,month:9,title:'Digital Task Cards That Preserve Control on the Hangar Floor',slug:'2025-09-digital-task-card-control',domain:'digital maintenance execution',challenge:'revisions, conditional steps, independent inspections, interruptions, offline work, findings, and sign-off must remain coherent under production pressure',design:'model step state, authority, effectivity, revision impact, and synchronization conflict explicitly',failure:'turning a paper card into a screen while leaving change control and findings outside the workflow',practice:'observe technicians through one complex card and design around interruptions and recovery',tags:['Digital task cards','Technician workflow','Execution control'],ata:[]},
  {year:2025,month:10,title:'Migrating MRO Workloads to Cloud Without Breaking Operational Continuity',slug:'2025-10-mro-cloud-migration',domain:'MRO cloud migration',challenge:'legacy integrations, batch windows, identity, latency, site connectivity, audit, and vendor constraints make a simple rehost operationally risky',design:'sequence migration by business capability with strangler interfaces, reconciliation, observability, and tested fallback',failure:'moving infrastructure while preserving brittle coupling and undocumented operational dependencies',practice:'baseline transaction paths and failure recovery before changing hosting or integration boundaries',tags:['Cloud migration','MRO integration','Resilience'],ata:[]},
  {year:2025,month:11,title:'Dispatch Reliability as a Decision System',slug:'2025-11-dispatch-reliability-decision-system',domain:'dispatch reliability improvement',challenge:'delays and cancellations are lagging outcomes produced by defects, stations, materials, planning, network pressure, and recovery decisions',design:'connect leading maintenance conditions to controllable interventions and retain the operational narrative around each event',failure:'ranking fleets by a single rate without exposure, confidence, or causal context',practice:'choose one delay driver and build a cross-functional intervention loop with measurable ownership',tags:['Dispatch reliability','Decision systems','Operational learning'],ata:[]},
  {year:2025,month:12,title:'Designing a Maintenance Copilot That Knows When to Stop',slug:'2025-12-maintenance-copilot-boundaries',domain:'maintenance AI assistance',challenge:'retrieval, summarization, case history, procedural control, uncertainty, and professional authority collide in one conversational interface',design:'constrain the copilot to evidence assembly, cited synthesis, explicit abstention, and role-aware handoff',failure:'allowing fluent generated text to resemble approved technical instruction',practice:'evaluate with adversarial maintenance scenarios and measure unsupported claims, corrections, and safe abstention',tags:['Maintenance copilots','AI safety','Evidence retrieval'],ata:[]}
];

const month = (value:number)=>String(value).padStart(2,'0');
export const historicalRecords: ArticleRecord[] = historicalIssues.map((issue,index)=>({
  id:`nbl-${issue.year}-${month(issue.month)}`,title:issue.title,slug:issue.slug,issueDate:`${issue.year}-${month(issue.month)}-01`,publishedAt:'2026-07-30T21:55:00-05:00',updatedAt:'2026-07-30T21:55:00-05:00',summary:`A whitepaper on ${issue.domain}: ${issue.design}.`,description:`A Northbound Labs engineering analysis of ${issue.domain}, its operational controls, failure modes, and implementation path.`,categories:['Aviation Maintenance','Engineering Practice'],topicTags:issue.tags,ataChapters:issue.ata,articleType:['Engineering Guide','Reference Architecture','Operating Model','Reliability Practice'][index%4],estimatedReadingTime:14,publicationStatus:'published',featuredStatus:'standard',diagramIdentifiers:[`${issue.slug}-context`,`${issue.slug}-sequence`,`${issue.slug}-risks`,`${issue.slug}-measures`],referenceCount:4,relatedArticleSlugs:[],previousArticleSlug:null,nextArticleSlug:null
}));
