export type IssueContent = {
  thesis: string; context: string[]; sections: { title: string; paragraphs: string[] }[];
  takeaways: string[]; references: { label: string; href: string }[];
  diagram: { title: string; caption: string; kind: 'architecture'|'data-flow'|'workflow'|'decision-tree'|'timeline'|'feedback-loop'|'event-pipeline'|'human-in-the-loop'|'aircraft-to-cloud'|'swimlane'; nodes: { id:string; label:string; detail?:string; x:number; y:number; tone?:'blue'|'orange'|'green'|'purple'|'red' }[]; edges: { from:string; to:string; label?:string; dashed?:boolean }[] };
};

const refs = {
  faa: { label: 'FAA aviation handbooks and manuals', href: 'https://www.faa.gov/regulations_policies/handbooks_manuals/aviation' },
  hf: { label: 'FAA Maintenance Human Factors', href: 'https://www.faa.gov/about/initiatives/maintenance_hf' },
  nasa: { label: 'NASA Technical Reports Server', href: 'https://ntrs.nasa.gov/' },
  aws: { label: 'AWS Well-Architected Framework', href: 'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html' },
  events: { label: 'AWS event-driven architecture guidance', href: 'https://docs.aws.amazon.com/lambda/latest/dg/concepts-event-driven-architectures.html' },
  nist: { label: 'NIST AI Risk Management Framework', href: 'https://www.nist.gov/itl/ai-risk-management-framework' },
  easa: { label: 'EASA Artificial Intelligence Roadmap 2.0', href: 'https://www.easa.europa.eu/en/document-library/general-publications/easa-artificial-intelligence-roadmap-20' },
  icao: { label: 'ICAO Safety Management Manual resources', href: 'https://www.icao.int/safety/SafetyManagement/Pages/Guidance-Material.aspx' }
};
const standardRefs = [refs.faa, refs.nasa, refs.aws, refs.icao];
const row = (labels: string[], tones: ('blue'|'orange'|'green'|'purple'|'red')[] = ['orange','blue','purple','green','red']) => labels.map((label, i) => ({ id:`n${i}`, label, x:35+i*190, y:i%2 ? 275 : 95, tone:tones[i%tones.length] }));
const chain = (count:number) => Array.from({length:count-1},(_,i)=>({from:`n${i}`,to:`n${i+1}`,label:i===count-2?'review':''}));

export const issueContent: Record<string, IssueContent> = {
  '2026-01-maintenance-decision-brief': {
    thesis: 'The right interface for maintenance intelligence is a compact, inspectable evidence brief—not an open-ended conversation that makes facts and inference difficult to distinguish.',
    context: ['Maintenance control works against a clock, but speed is useful only when the evidence remains visible. Controllers often reconstruct a case across a technical log, maintenance history, current configuration, manuals, operational constraints, and telephone calls. A generic chatbot can shorten the prose while making the provenance harder to see.', 'A decision brief changes the design target. It treats the product as a controlled assembly of observed condition, effectivity, history, procedural references, uncertainty, and accountable disposition. The machine prepares the case; qualified personnel decide what the case means.'],
    sections: [
      {title:'Design around inspection, not conversation',paragraphs:['A controller should be able to scan the brief in a predictable order: what changed, where the evidence came from, what is known about the tail, what similar events occurred, and what information remains missing. Stable placement matters during disruption and shift handover.','Generated language belongs in a clearly marked assessment panel. Recorded facts should retain source, timestamp, and link. A hypothesis must never acquire the visual authority of an approved instruction simply because it is fluent.']},
      {title:'Make uncertainty operational',paragraphs:['A single confidence percentage compresses several different questions. Evidence coverage, source freshness, fleet similarity, contradictory signals, and model applicability should be shown separately. That lets the reviewer decide whether to investigate, wait for better evidence, or dismiss the suggestion.','The system should also explain absence. Missing component history, unresolved aircraft identity, or an out-of-date document is a product condition—not blank space that the model is invited to fill.']},
      {title:'Fit the authority structure',paragraphs:['The brief can propose a review path, but it cannot confer authority. Inspection, troubleshooting, deferment, and return-to-service actions remain governed by approved data, company procedures, and authorized roles. The interface should record who reviewed the evidence, what disposition was selected, and why.','Role-aware controls keep drafting, review, approval, and execution distinct. Override must be easy, explicit, and captured as feedback rather than treated as user failure.']},
      {title:'Failure modes and practical rollout',paragraphs:['Common failures include overlong summaries, hidden source conflicts, stale technical content, and alerts that arrive without an operational owner. Another failure is measuring clicks instead of whether the brief improved evidence completeness or decision latency.','Begin with one repeatable MCC decision and a small reviewer group. Observe actual handovers, revise the information hierarchy, and measure corrections. Expand only after source quality and disposition capture are dependable.']}
    ],
    takeaways:['Keep facts, inference, and approved action visually distinct.','Show missing evidence and conflicts rather than smoothing them away.','Measure reviewer corrections and downstream outcomes.'], references:[refs.hf,refs.faa,refs.nist,refs.icao],
    diagram:{title:'Anatomy of an inspectable maintenance decision brief',caption:'The visual hierarchy moves from recorded condition to accountable disposition. Machine assessment is deliberately placed between evidence and authority—not above either.',kind:'human-in-the-loop',nodes:row(['Observed condition','Tail + effectivity','Relevant history','Machine assessment','Human disposition']),edges:chain(5)}
  },
  '2026-02-event-driven-aircraft-telemetry': {
    thesis:'Aircraft telemetry becomes trustworthy when the platform preserves event identity and time before it optimizes throughput or adds analytics.',
    context:['An aircraft message is not merely a payload. Its operational meaning depends on tail, configuration, flight leg, phase, component position, source system, and the clocks used along its journey. A streaming platform that loses those relationships delivers data quickly and understanding late.','The backbone should therefore act as a chain of custody. It accepts imperfect edge connectivity, keeps an immutable envelope, resolves context through explicit versions, and makes replay a normal engineering operation.'],
    sections:[
      {title:'Use an aviation event envelope',paragraphs:['Every event needs a stable identifier, source event time, ingestion time, aircraft identity, schema version, quality state, and source lineage. Payloads should remain close to their recorded form while normalized interpretations are stored separately.','This separation allows a parser or reference-data correction to be replayed without rewriting history. It also helps investigators distinguish what the aircraft sent from what a downstream service inferred.']},
      {title:'Engineer for intermittent paths',paragraphs:['Airborne and airport connectivity is variable by design context. Producers need bounded buffering, retry behavior, idempotent acceptance, and sequence information. Consumers must tolerate late and duplicated events without quietly manufacturing order.','Partitioning by aircraft or flight leg can preserve useful ordering, but the key should follow the decision being supported. A global order is expensive, generally false, and rarely necessary.']},
      {title:'Make quality observable',paragraphs:['Freshness, completeness, invalid schema rate, unresolved tails, duplicate rate, and late arrival should be operational measures. A green broker dashboard says little about whether engineering received a coherent flight.','Quarantine is preferable to silent coercion. Bad events should remain inspectable, recoverable, and connected to the rule that rejected them. Quality teams need a repair and replay workflow.']},
      {title:'Failure modes and delivery sequence',paragraphs:['Typical failures include coupling every consumer to an OEM payload, deleting late data, treating ingestion time as event time, and allowing reference-data changes to alter old results without a trace.','Start with one source and one downstream decision. Establish envelope, raw retention, identity resolution, replay, and service objectives before adding more feeds. Scale is easier after meaning is stable.']}
    ], takeaways:['Preserve source events and derived interpretations separately.','Design duplicates, delay, and replay as normal conditions.','Measure semantic completeness as well as infrastructure health.'],references:[refs.aws,refs.events,refs.nasa,refs.icao],
    diagram:{title:'Aircraft-to-cloud event chain of custody',caption:'Each handoff adds operational context without overwriting the source record. The repair loop makes quarantine and replay an explicit production capability.',kind:'aircraft-to-cloud',nodes:row(['Aircraft source','Edge buffer','Immutable intake','Context service','Engineering product']),edges:chain(5)}
  },
  '2026-03-chronic-defect-intelligence': {
    thesis:'Chronic-defect intelligence should assemble reviewable cases across time and configuration; it should not declare chronicity from text similarity alone.',
    context:['Repeat discrepancies hide behind inconsistent language, changing component positions, station practices, and corrective actions that addressed symptoms rather than causes. Reliability engineers already perform the difficult work of joining these clues. Technology should make that reasoning easier to inspect, not replace it with an unexplained score.','A case builder groups candidate evidence, states why it was grouped, and keeps counter-evidence visible. The reliability program retains ownership of thresholds, escalation, and corrective action.'],
    sections:[
      {title:'Build the engineering identity first',paragraphs:['Tail, ATA context, component position, part and serial history, flight cycles, and configuration effective dates create the spine of a case. Free text adds useful symptoms only after these identities are resolved.','Normalization should preserve original wording alongside controlled terms. Engineers need to see whether a grouping came from shared equipment, temporal proximity, symptom semantics, or a known rule.']},
      {title:'Separate recurrence from significance',paragraphs:['Frequency alone does not establish operational significance. Exposure, severity, dispatch consequence, corrective-action diversity, and fleet comparison provide context. A low-frequency pattern can deserve review while a common nuisance message may not.','The product should offer several lenses rather than one composite ranking. This prevents a convenient number from hiding the policy choices embedded in weighting.']},
      {title:'Put the engineer inside the loop',paragraphs:['Reliability engineers should merge or split cases, correct classification, record rationale, and promote a case into formal program governance. Those actions become labeled operational knowledge for later evaluation.','The case view should show a timeline from write-up through troubleshooting, removals, shop findings, and recurrence. Missing outcomes remain visible because unknown is not equivalent to no fault.']},
      {title:'Failure modes and implementation',paragraphs:['Keyword-only grouping, unversioned thresholds, and rankings without exposure are common analytical traps. Another is automating escalation before the organization agrees on ownership and review cadence.','Begin with a known family of repeat events. Compare system-created cases with engineer reconstruction, document false joins and missed joins, then refine identity and terminology before widening scope.']}
    ],takeaways:['Use configuration and component identity as the case spine.','Explain every grouping and preserve counter-evidence.','Keep formal chronic-defect determination within reliability governance.'],references:standardRefs,
    diagram:{title:'From scattered events to a governed defect case',caption:'Evidence converges into a reviewable case, then moves through engineering governance. The return path records case corrections and confirmed outcomes.',kind:'feedback-loop',nodes:row(['Discrepancies','Identity resolution','Candidate case','Reliability review','Confirmed outcome']),edges:[...chain(5),{from:'n4',to:'n1',label:'learn',dashed:true}]}
  },
  '2026-04-maintenance-knowledge-retrieval': {
    thesis:'Maintenance retrieval is a document-control problem before it is a language-model problem.',
    context:['A semantically relevant paragraph may still be unusable because it is obsolete, not effective for the aircraft, outside the user’s authority, or detached from the procedure that gives it meaning. Retrieval quality in maintenance therefore requires controlled metadata and enforceable eligibility rules.','The system should narrow the eligible corpus before semantic ranking, return citations at the passage and document level, and abstain when it cannot establish effectivity or authority.'],
    sections:[
      {title:'Control the corpus',paragraphs:['Each source needs document identity, revision, approval state, effectivity, supersession relationship, access class, and ingestion lineage. Chunking must preserve section, warning, caution, table, and figure relationships.','A synchronization pipeline should detect change and withdrawal. Deleting an old vector is insufficient; the platform needs an auditable record of what became eligible, when, and under which policy.']},
      {title:'Filter before ranking',paragraphs:['Aircraft and component effectivity, document status, role, and operator context are hard constraints. Semantic similarity should rank only within the material the user is permitted and expected to consider.','Queries also need operational context. A fault message, tail, phase, and recent work history can improve retrieval more reliably than asking the user to craft an elaborate prompt.']},
      {title:'Design the answer for verification',paragraphs:['The response should pair each claim with a direct source link, revision, effective context, and quoted passage kept within appropriate limits. Recorded content and generated synthesis need different visual treatment.','When sources conflict or eligibility cannot be resolved, the system should say so. Abstention is a successful control behavior, not a model failure to be optimized away.']},
      {title:'Failure modes and rollout',paragraphs:['Dangerous patterns include indexing uncontrolled exports, hiding revision status, generating across incompatible effectivities, and evaluating answers only for fluency.','Start with a bounded, well-controlled collection and a named user task. Test retrieval eligibility, citation correctness, conflict handling, and abstention with technical authors and end users before broadening the corpus.']}
    ],takeaways:['Enforce effectivity and approval before semantic ranking.','Preserve structural context, warnings, and revision lineage.','Treat citation and abstention as core product behavior.'],references:[refs.faa,refs.nist,refs.aws,refs.easa],
    diagram:{title:'Controlled retrieval path from question to evidence',caption:'Eligibility gates precede semantic ranking. The final answer remains connected to controlled passages, revision state, and explicit abstention.',kind:'decision-tree',nodes:row(['Operational query','Eligibility gate','Evidence ranking','Cited synthesis','Qualified review']),edges:chain(5)}
  },
  '2026-08-maintenance-observability': {
    thesis:'Maintenance data products need observability of meaning and delivery, not only servers, queues, and model endpoints.',
    context:['A technically healthy pipeline can still provide the wrong tail mapping, stale configuration, incomplete flight data, or a model result that never reached the maintenance workflow. Conventional infrastructure telemetry sees only part of that failure surface.','Maintenance observability joins platform signals with data contracts, semantic checks, model behavior, workflow delivery, and user disposition. It makes the evidence path inspectable end to end.'],
    sections:[
      {title:'Define the decision service level',paragraphs:['Service objectives should start from the consumer: by what point must which evidence be complete enough for which decision? This produces useful measures for freshness, flight completeness, identity resolution, and delivery.','Averages are misleading. Teams should segment by fleet, station, source, and operating condition so that a small but important population does not disappear inside aggregate green.']},
      {title:'Observe semantic drift',paragraphs:['Schema validity cannot detect a source field whose operational meaning changed. Distribution shifts, new fault codes, configuration changes, and altered station practices require domain-aware monitors and release notes.','Reference data deserves the same operational discipline as application code. Mapping changes should be versioned, reviewed, tested against representative tails, and connected to downstream impact.']},
      {title:'Connect models to workflow outcomes',paragraphs:['Model latency and error rate are necessary but incomplete. Teams also need evidence coverage, abstention, correction, false escalation, missed significant cases, and whether the result arrived in time to matter.','A trace identifier should connect source events, transformations, inference, retrieved evidence, the displayed brief, reviewer action, and confirmed outcome. That is the unit of operational debugging.']},
      {title:'Failure modes and operating rhythm',paragraphs:['Dashboard sprawl, thresholds without owners, and alerts that cannot identify affected aircraft create performative observability. Another trap is collecting sensitive data without clear retention and access controls.','Establish a daily exception review and a weekly product-quality review. Assign ownership by decision path, publish error budgets, and use incidents to improve contracts rather than merely restart services.']}
    ],takeaways:['Measure whether evidence arrived complete and in time for the decision.','Version and monitor semantic mappings.','Trace outcomes across infrastructure, data, models, and workflow.'],references:[refs.aws,refs.nist,refs.nasa,refs.icao],
    diagram:{title:'Maintenance evidence observability control room',caption:'Four observability planes converge on a decision-path trace, giving operators a coherent view of technical health and operational consequence.',kind:'architecture',nodes:row(['Source health','Semantic quality','Model behavior','Workflow delivery','Decision trace']),edges:chain(5)}
  },
  '2026-09-digital-work-package-orchestration': {
    thesis:'A digital work package is a controlled lifecycle shared across planning, materials, production, engineering, and records—not a PDF bundle with electronic signatures.',
    context:['Work packages gather task requirements, effectivity, skills, materials, tooling, access, findings, revisions, deferrals, and completion evidence. When these elements live in disconnected queues, planners compensate with spreadsheets and technicians discover conflicts at the aircraft.','Orchestration should expose state and dependencies while leaving authoritative transactions in approved systems. Events coordinate the lifecycle; they do not bypass production control.'],
    sections:[
      {title:'Model states and obligations',paragraphs:['A package moves through proposed, scoped, planned, ready, released, active, interrupted, completed, reviewed, and closed states. Each transition has entry criteria, responsible role, evidence, and permitted rollback.','Readiness is not a single checkbox. Material, tooling, data, access, labor, and aircraft conditions should be visible separately so risk is understood before release.']},
      {title:'Carry effectivity and revision',paragraphs:['Tasks and engineering instructions can change after planning begins. The package needs a controlled baseline plus an impact workflow that identifies affected work, completed steps, and required re-briefing.','Technicians must see why an item changed and which version governs their execution. Offline behavior should preserve the last controlled state and make synchronization conflicts explicit.']},
      {title:'Capture findings as first-class events',paragraphs:['A finding can create non-routine work, demand material, request engineering support, alter access, or block closeout. Treating it as free-text annotation delays every downstream decision.','Structured findings should retain technician narrative and attachments while emitting governed events to the appropriate owners. Closure links the resolution back to the originating task and aircraft record.']},
      {title:'Failure modes and rollout',paragraphs:['Digitizing a broken handoff, creating a shadow system of record, and hiding package readiness behind one percentage are common failures. So is assuming constant connectivity in the hangar.','Begin with one check type and map the real handoffs on the floor. Introduce visible state and dependency ownership first, then automate notifications and integrations after the operating model is accepted.']}
    ],takeaways:['Treat readiness as explicit dependent conditions.','Version the released baseline and manage change impact.','Connect every finding to ownership and closure evidence.'],references:standardRefs,
    diagram:{title:'Digital work-package responsibility flow',caption:'The package crosses planning, production, engineering, and records with explicit control points. State is shared; authority remains with the responsible function.',kind:'swimlane',nodes:row(['Scope + plan','Readiness review','Execute work','Resolve findings','Records close']),edges:chain(5)}
  },
  '2026-10-maintenance-ai-governance': {
    thesis:'Governance should change the controls applied to a product according to operational consequence; one approval maze for every experiment protects neither safety nor innovation.',
    context:['Maintenance AI spans low-consequence search aids, analytical prioritization, workflow recommendations, and capabilities close to safety-sensitive decisions. Treating them alike produces either weak controls or unusable bureaucracy.','A risk-tiered system makes evidence, evaluation, release authority, monitoring, and override proportional to what the product can influence and how easily a human can detect error.'],
    sections:[
      {title:'Classify the operational influence',paragraphs:['Teams should document the decision supported, users, affected assets, data sensitivity, output path, human review, error detectability, and worst credible misuse. Classification belongs to the use case, not the model name.','Changing where an output appears or who may act on it can change risk even when code does not. Product and workflow releases therefore need governance alongside model releases.']},
      {title:'Build an evidence case',paragraphs:['The release record should include intended use, exclusions, source lineage, evaluation design, representative scenarios, known limitations, security review, rollback, and accountable owners.','Evaluation must include retrieval failures, missing data, distribution change, misleading confidence, automation bias, and handover pressure—not only average benchmark accuracy.']},
      {title:'Monitor authority and behavior',paragraphs:['Production controls should enforce roles, citations, versioning, approval, and retention. Monitoring should show corrections, override, abstention, false escalation, and signs that users are over-relying on output.','A kill switch without an operating decision is theater. Teams need named authority to restrict or withdraw capability, a communication path, and a tested fallback workflow.']},
      {title:'Failure modes and practical adoption',paragraphs:['Policy-only governance, unowned inventories, and committees reviewing screenshots instead of evidence are recurring failures. Excessive process also drives experimentation into unmanaged tools.','Publish a small number of risk tiers and required artifacts. Review real products with maintenance, safety, security, data, and engineering leaders; refine controls from experience and record decisions transparently.']}
    ],takeaways:['Classify the use case and workflow, not merely the model.','Require evidence proportional to operational influence.','Make restriction, rollback, and fallback executable.'],references:[refs.nist,refs.easa,refs.faa,refs.icao],
    diagram:{title:'Risk-tiered control gates for maintenance AI',caption:'The governance path increases rigor as operational influence rises. Monitoring and withdrawal authority continue after release.',kind:'workflow',nodes:row(['Use-case intake','Risk classification','Evidence review','Release authority','Operational monitor']),edges:chain(5)}
  },
  '2026-11-maintenance-outcome-learning': {
    thesis:'A maintenance intelligence platform cannot learn from predictions; it learns from carefully defined operational outcomes and the uncertainty around them.',
    context:['A component removal is not proof that an alert was correct. A no-fault-found shop result is not proof that the aircraft had no intermittent condition. Outcomes emerge across troubleshooting, deferment, removal, inspection, shop findings, recurrence, and later reliability review.','The platform needs an outcome vocabulary that preserves ambiguity and a feedback process owned jointly by maintenance, reliability, and data teams.'],
    sections:[
      {title:'Define an outcome chain',paragraphs:['Link the surfaced condition to reviewer disposition, executed action, technician finding, installed or removed component, shop result, subsequent operation, and recurrence window. Each step has its own timestamp and confidence.','This chain prevents teams from selecting a convenient proxy as ground truth. It also reveals where the organization loses visibility after a handoff.']},
      {title:'Preserve unknown and contested states',paragraphs:['Outcome labels should include confirmed, not confirmed, inconclusive, insufficient evidence, action changed condition, and pending follow-up. Forced binary labels create false certainty and corrupt evaluation.','Reliability engineers need a way to revise conclusions when later evidence arrives. Revisions should be additive and versioned so prior evaluation can be reproduced.']},
      {title:'Use feedback at several cadences',paragraphs:['Operational teams need rapid feedback on alert usefulness and workflow friction. Model owners need periodic evaluation by cohort. Reliability governance needs longer-horizon pattern and recurrence review.','Separating these cadences prevents a quick user dismissal from becoming a definitive technical label while still allowing the product team to fix poor presentation.']},
      {title:'Failure modes and implementation',paragraphs:['Common errors include equating removal with confirmation, dropping inconclusive events, training on self-generated labels, and measuring only cases where action occurred.','Start with one use case and trace twenty cases manually across systems. Build the minimum outcome chain, assign stewardship, and publish label quality before using the data for automated learning.']}
    ],takeaways:['Model the full chain from signal to later recurrence.','Keep inconclusive and revised outcomes.','Separate operational feedback from technical ground truth.'],references:standardRefs,
    diagram:{title:'Reliability outcome learning loop',caption:'Operational evidence moves through action and confirmation before returning to product and program governance. Dashed feedback signals reviewed learning, not automatic retraining.',kind:'feedback-loop',nodes:row(['Signal surfaced','Human disposition','Work performed','Outcome reviewed','Program learning']),edges:[...chain(5),{from:'n4',to:'n0',label:'governed feedback',dashed:true}]}
  },
  '2026-12-maintenance-intelligence-operating-system': {
    thesis:'Maintenance intelligence becomes durable only when product, data, engineering, reliability, and operational authority work as one managed system.',
    context:['A portfolio of dashboards and models does not create intelligence. The organization needs a repeatable way to select decisions, establish evidence ownership, place assistance in controlled workflows, measure outcomes, and retire capabilities that do not earn trust.','The operating system is socio-technical: governance, service ownership, architecture, human factors, and reliability learning reinforce one another. Its purpose is not autonomy. Its purpose is better-supported action.'],
    sections:[
      {title:'Organize around decision products',paragraphs:['Each product should name the decision, user, evidence contract, authority boundary, delivery moment, outcome, and service owner. Shared platform teams provide identity, event, lineage, retrieval, and observability capabilities without owning operational meaning.','This arrangement avoids two extremes: duplicated point solutions and a central platform disconnected from maintenance work. Domain product teams remain accountable for usefulness and safe integration.']},
      {title:'Create an evidence supply chain',paragraphs:['Sources, reference data, transformations, rules, models, retrieved documents, and generated summaries form a supply chain. Contracts and trace identifiers allow teams to assess completeness and find where meaning changed.','The authoritative record stays in approved operational systems. Intelligence products retain enough lineage to reproduce what a reviewer saw and why it appeared at that time.']},
      {title:'Operate trust deliberately',paragraphs:['Trust is earned through predictable behavior, visible uncertainty, responsive correction, and clear authority. Training cannot compensate for a product that hides sources or produces unowned alerts.','Service reviews should combine platform reliability, semantic quality, user corrections, operational outcomes, safety observations, and unresolved risks. Leadership then has a portfolio view grounded in evidence.']},
      {title:'Failure modes and a durable roadmap',paragraphs:['Programs fail when they chase use-case volume, centralize every decision, or treat pilot success as production readiness. They also fail when no team owns data repair and outcome capture.','Build the common evidence path while delivering a small number of decision products. Fund operations, stewardship, and decommissioning. Scale only the capabilities that demonstrate workflow adoption, traceability, and credible outcome value.']}
    ],takeaways:['Fund decision products and shared evidence capabilities together.','Keep operational authority and system-of-record boundaries explicit.','Scale through measured trust, not use-case count.'],references:[refs.faa,refs.aws,refs.nist,refs.icao],
    diagram:{title:'The maintenance intelligence operating system',caption:'Decision products sit on a common evidence foundation and remain enclosed by authority, observability, and reliability-learning controls.',kind:'architecture',nodes:row(['Evidence supply','Decision services','Human workflow','Outcome system','Portfolio review']),edges:[...chain(5),{from:'n4',to:'n0',label:'strategy',dashed:true}]}
  }
};
