import { notFound } from 'next/navigation';
import { ArticleShell } from './ArticleShell';
import { ExecutiveSummary, KeyTakeaways, ReferenceList } from './Publication';
import { PublicationVisual, type PublicationVisualContext } from '../../src/components/publication';
import { getArticle } from '../lib/articles';
import { historicalIssues } from '../lib/historicalCatalog';

const references = [
  ['FAA aviation handbooks and manuals','https://www.faa.gov/regulations_policies/handbooks_manuals/aviation'],
  ['FAA Maintenance Human Factors resources','https://www.faa.gov/about/initiatives/maintenance_hf'],
  ['NASA Technical Reports Server','https://ntrs.nasa.gov/'],
  ['ICAO safety-management guidance material','https://www.icao.int/safety/SafetyManagement/Pages/Guidance-Material.aspx']
];

export function HistoricalArticle({slug}:{slug:string}){
  const issue=historicalIssues.find((item)=>item.slug===slug);if(!issue)notFound();const article=getArticle(slug);
  const visualContext:PublicationVisualContext={slug,title:article.title,domain:issue.domain,tags:issue.tags,ata:issue.ata,issueDate:article.issueDate,brief:`${issue.challenge}. ${issue.design}. Failure mode: ${issue.failure}.`};
  return <ArticleShell article={article}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.description,datePublished: article.publishedAt,dateModified:article.updatedAt||article.publishedAt,mainEntityOfPage:`https://northboundlabs.ai/articles/${slug}`,publisher:{'@type':'Organization',name:'Northbound Labs'}})}}/>
    <ExecutiveSummary><p>The central problem in {issue.domain} is not a shortage of technology. It is that {issue.challenge}. A useful design must preserve operational meaning while making the next decision easier to inspect.</p><p>This paper proposes a bounded approach: {issue.design}. The intent is decision support with explicit evidence and accountable authority—not an automated substitute for approved maintenance data, engineering judgment, or licensed action.</p></ExecutiveSummary>
    <PublicationVisual context={visualContext} role="hero"/>
    <section><h2>1. Define the operational decision</h2><p>Programs often begin by collecting available data or selecting a platform. That reverses the useful order. The team should first identify who must decide, when the decision occurs, which evidence is authoritative, what uncertainty is acceptable, and which action remains under qualified control.</p><p>For {issue.domain}, the dominant constraint is that {issue.challenge}. The product boundary should therefore be written as a decision contract: inputs, freshness, effectivity, interpretation rules, exclusions, reviewer role, downstream record, and measurable outcome. This contract gives engineering and operations a shared definition of done.</p><PublicationVisual context={visualContext} role="evidence"/></section>
    <section><h2>2. Preserve evidence before interpretation</h2><p>Source records should retain identity, event time, ingestion time, configuration context, revision, lineage, and quality state. Normalized concepts are valuable, but they should never overwrite what the source actually reported. Investigators need to reproduce the view that existed when a decision was made.</p><p>The recommended design is to {issue.design}. Derived features, rules, statistical output, retrieved text, and generated synthesis should be distinguishable in storage and in the user interface. That separation supports correction without rewriting history and allows reviewers to challenge an inference while accepting the underlying evidence.</p><PublicationVisual context={visualContext} role="analysis"/></section>
    <section><h2>3. Engineer the authority boundary</h2><p>Operational software can assemble context, identify patterns, rank attention, and prepare a structured brief. It cannot create maintenance authority. The interface must identify the governing source, effective revision, responsible role, and required disposition. Override and abstention are normal system behaviors.</p><p>The most important anti-pattern is {issue.failure}. It tends to appear efficient because ambiguity disappears from the screen. In reality the ambiguity has only been hidden from the person accountable for the decision. Controls should make missing context, conflict, and inapplicability prominent enough to change behavior.</p><PublicationVisual context={visualContext} role="decision"/></section>
    <section><h2>4. Implementation, governance, and limitations</h2><p>A credible first release should {issue.practice}. The team should conduct prospective shadow use, compare product output with actual engineering reconstruction, and record why reviewers accept, modify, or reject the result. Expansion should depend on evidence quality and workflow value rather than demonstration appeal.</p><p>Governance belongs in the service itself: access control, source eligibility, versioning, release evidence, monitoring, rollback, retention, and outcome stewardship. Limitations should be published by fleet, configuration, operating regime, source availability, and decision type. When applicability cannot be established, the safe result is a visible abstention.</p><p>Measures should connect technical behavior to the decision contract. Useful families include evidence completeness, freshness, unresolved identity, reviewer correction, false escalation, missed significant cases, decision latency, recurrence, and outcome-linkage quality. These measures are meaningful only when segmented by the operational conditions that influence them.</p></section>
    <KeyTakeaways><ul><li>Begin with a named decision, accountable role, and evidence contract.</li><li>Preserve recorded facts separately from normalization and inference.</li><li>Design explicitly against {issue.failure}.</li><li>{issue.practice.charAt(0).toUpperCase()+issue.practice.slice(1)}.</li></ul></KeyTakeaways>
    <ReferenceList>{references.map(([label,href])=><li key={href}><a href={href} target="_blank" rel="noreferrer">{label}</a></li>)}</ReferenceList>
  </ArticleShell>
}
