import { ArticleShell } from './ArticleShell';
import { ExecutiveSummary, KeyTakeaways, ReferenceList } from './Publication';
import { getArticle } from '../lib/articles';
import { issueContent } from '../lib/issueContent';
import { PublicationVisual, type PublicationVisualContext } from '../../src/components/publication';

export function IssueArticle({ slug }: { slug: string }) {
  const article = getArticle(slug); const content = issueContent[slug];
  if (!content) throw new Error(`Missing issue content: ${slug}`);
  const visualContext:PublicationVisualContext={slug,title:article.title,domain:article.categories.join(' · '),tags:article.topicTags,ata:article.ataChapters,issueDate:article.issueDate};
  return <ArticleShell article={article}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.description,datePublished: article.publishedAt,dateModified:article.updatedAt || article.publishedAt,mainEntityOfPage:`https://northboundlabs.ai/articles/${slug}`,publisher:{'@type':'Organization',name:'Northbound Labs'}})}} />
    <ExecutiveSummary><p>{content.thesis}</p>{content.context.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</ExecutiveSummary>
    <PublicationVisual context={visualContext} role="hero"/>
    {content.sections.map((section, index) => <section key={section.title}><h2>{index + 1}. {section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{index<3?<PublicationVisual context={visualContext} role={(['evidence','analysis','decision'] as const)[index]}/>:null}</section>)}
    <section className="decision-checklist"><h2>Implementation decision checklist</h2><p>Before this design moves from a whiteboard into an operational maintenance workflow, the delivery team should test the complete decision path against the article&apos;s central thesis: {content.thesis} The review should be conducted with the people who own the evidence, the technical interpretation, the operational decision, and the resulting aircraft record.</p><ul><li><strong>Decision:</strong> Name the exact maintenance decision, its deadline, the accountable role, and the approved action boundary.</li><li><strong>Evidence:</strong> Identify authoritative sources, effectivity, freshness, lineage, known gaps, and the conditions that require abstention.</li><li><strong>Interpretation:</strong> Separate recorded facts, normalized concepts, deterministic rules, analytical estimates, and generated language in both storage and presentation.</li><li><strong>Failure:</strong> Exercise missing data, late delivery, identity conflict, stale documents, unusual configuration, user correction, and service outage.</li><li><strong>Authority:</strong> Confirm that qualified personnel can inspect, challenge, override, escalate, and record disposition without working around the product.</li><li><strong>Learning:</strong> Define the downstream finding, outcome steward, recurrence window, review cadence, and criteria for changing or withdrawing the capability.</li></ul><p>Release evidence should cover the operating scenarios described in <em>{content.sections[0].title}</em> and the controls established in <em>{content.sections[content.sections.length-1].title}</em>. A technically successful service is not ready if the workflow cannot identify an owner, reproduce the evidence shown to the reviewer, or recover safely when a dependency fails. Reviewers should also record unresolved assumptions, degraded operating modes, and the evidence that would trigger reassessment. Expansion should follow demonstrated decision quality and traceability—not the number of data sources connected.</p></section>
    <KeyTakeaways><ul>{content.takeaways.map((takeaway) => <li key={takeaway}>{takeaway}</li>)}</ul></KeyTakeaways>
    <ReferenceList>{content.references.map((reference) => <li key={reference.href}><a href={reference.href} target="_blank" rel="noreferrer">{reference.label}</a></li>)}</ReferenceList>
  </ArticleShell>;
}

export function issueMetadata(slug: string) { const article = getArticle(slug); return { title: article.title, description: article.description, alternates:{canonical:`/articles/${slug}`}, openGraph:{type:'article' as const,title:article.title,description:article.description,publishedTime:article.publishedAt,modifiedTime:article.updatedAt || article.publishedAt} }; }
