'use client';
import { useMemo } from 'react';
import { ReactFlow, Background, Controls, Handle, Position, MarkerType, type Node, type Edge, type NodeProps } from '@xyflow/react';
import { Plane, Radio, Database, ShieldCheck, Wrench, FileCheck2, Gauge, Cloud, Network, UserCheck, Boxes, History, Search, Workflow, CircleCheck, TriangleAlert, PackageCheck, ServerCog } from 'lucide-react';
import '@xyflow/react/dist/style.css';

type Variant='cloud'|'aircraft'|'reliability'|'records'|'security'|'asset';
type NodeData={label:string;detail:string;icon:keyof typeof icons;index?:number};
const icons={plane:Plane,radio:Radio,database:Database,shield:ShieldCheck,wrench:Wrench,file:FileCheck2,gauge:Gauge,cloud:Cloud,network:Network,user:UserCheck,boxes:Boxes,history:History,search:Search,workflow:Workflow,check:CircleCheck,alert:TriangleAlert,package:PackageCheck,server:ServerCog};

function ServiceNode({data}:NodeProps<Node<NodeData>>){const Icon=icons[data.icon]||Boxes;return <div className="ref-node"><Handle type="target" position={Position.Left}/><div className="ref-node-icon"><Icon size={19} strokeWidth={1.7}/></div><div><span>{data.index?String(data.index).padStart(2,'0'):'SERVICE'}</span><strong>{data.label}</strong><small>{data.detail}</small></div><Handle type="source" position={Position.Right}/></div>}
const nodeTypes={service:ServiceNode};
const group=(id:string,label:string,x:number,y:number,w:number,h:number,tone:string):Node=>({id,type:'group',position:{x,y},data:{label},style:{width:w,height:h},className:`ref-group ref-group-${tone}`,selectable:false,draggable:false});
const service=(id:string,label:string,detail:string,icon:NodeData['icon'],x:number,y:number,parentId?:string,index?:number):Node<NodeData>=>({id,type:'service',position:{x,y},parentId,extent:parentId?'parent':undefined,data:{label,detail,icon,index},draggable:false,selectable:false});
const edge=(source:string,target:string,label?:string,dashed=false):Edge=>({id:`${source}-${target}`,source,target,label,type:'step',markerEnd:{type:MarkerType.ArrowClosed,width:14,height:14},className:dashed?'ref-edge ref-edge-dashed':'ref-edge',labelStyle:{fontSize:10,fontWeight:700,fill:'#334155'},labelBgStyle:{fill:'#fff',fillOpacity:.9}});

function blueprint(variant:Variant,domain:string):{nodes:Node[];edges:Edge[]} {
  if(variant==='cloud')return {nodes:[group('edge','AIRCRAFT + ENTERPRISE SOURCES',20,55,220,470,'slate'),group('region','CLOUD DECISION PLATFORM',285,25,560,530,'blue'),group('ops','OPERATIONAL CONSUMERS',890,55,210,470,'green'),service('aircraft','Aircraft events','messages · parameters','plane',24,55,'edge',1),service('mro','MRO records','work · parts · status','database',24,180,'edge',2),service('docs','Controlled content','revision · effectivity','file',24,305,'edge',3),service('ingest','Ingestion boundary','validate · quarantine','shield',35,65,'region',4),service('events','Domain event bus','order · replay','network',295,65,'region',5),service('history','Evidence store','raw · contextualized','database',35,230,'region',6),service('decision','Decision services',domain,'server',295,230,'region',7),service('trace','Lineage + controls','identity · audit','history',165,385,'region',8),service('mcc','Maintenance control','triage · disposition','user',18,65,'ops',9),service('eng','Engineering','investigate · approve','wrench',18,200,'ops',10),service('rel','Reliability','trend · govern','gauge',18,335,'ops',11)],edges:[edge('aircraft','ingest','telemetry'),edge('mro','ingest','transactions'),edge('docs','ingest','controlled'),edge('ingest','events'),edge('events','decision'),edge('ingest','history'),edge('history','decision'),edge('decision','trace','evidence'),edge('decision','mcc'),edge('decision','eng'),edge('decision','rel'),edge('rel','trace','outcome',true)]};
  if(variant==='aircraft')return {nodes:[group('airframe','AIRCRAFT SYSTEM BOUNDARY',30,40,660,500,'blue'),group('ground','GROUND ENGINEERING BOUNDARY',750,40,340,500,'green'),service('sensor','System sources','sensors · BITE · state','radio',30,70,'airframe',1),service('control','Control logic','mode · command','server',245,70,'airframe',2),service('effect','Physical response','position · pressure','gauge',460,70,'airframe',3),service('report','Flight evidence','phase · environment','plane',30,260,'airframe',4),service('capture','Event recorder','time · sequence','database',245,260,'airframe',5),service('message','Health messages','fault · status','alert',460,260,'airframe',6),service('context','Context resolver','tail · standard · ATA','search',35,75,'ground',7),service('case','Engineering case',domain,'wrench',35,230,'ground',8),service('outcome','Confirmed finding','action · recurrence','check',35,385,'ground',9)],edges:[edge('sensor','control'),edge('control','effect'),edge('sensor','capture'),edge('report','capture'),edge('control','message'),edge('effect','message'),edge('capture','context','recorded'),edge('message','context','reported'),edge('context','case'),edge('case','outcome'),edge('outcome','context','feedback',true)]};
  if(variant==='records')return {nodes:[group('create','EVIDENCE CREATION',25,55,260,450,'slate'),group('control','CONTROLLED RECORD CHAIN',340,30,470,500,'blue'),group('use','ACCEPTANCE + USE',865,55,220,450,'green'),service('task','Task execution','steps · measurements','wrench',30,75,'create',1),service('sign','Signed event','role · time · authority','user',30,245,'create',2),service('manifest','Expected manifest','required evidence','package',35,55,'control',3),service('identity','Identity + effectivity','aircraft · task · part','search',255,55,'control',4),service('revision','Revision lineage','supersedes · corrects','history',35,235,'control',5),service('exception','Exception queue','missing · ambiguous','alert',255,235,'control',6),service('accepted','Accepted record','complete · auditable','file',20,100,'use',7),service('status','Aircraft status','authoritative update','check',20,290,'use',8)],edges:[edge('task','manifest'),edge('sign','manifest'),edge('manifest','identity'),edge('identity','revision'),edge('revision','exception','verify'),edge('identity','accepted'),edge('exception','accepted','resolved'),edge('accepted','status')]};
  if(variant==='security')return {nodes:[group('external','EXTERNAL TRUST ZONE',20,60,250,440,'slate'),group('platform','CONTROLLED PLATFORM ZONE',325,25,520,520,'blue'),group('operation','MAINTENANCE AUTHORITY ZONE',900,60,200,440,'green'),service('partner','Partner systems','OEM · vendor · lessor','cloud',28,85,'external',1),service('device','Field devices','mobile · station','radio',28,260,'external',2),service('gateway','Identity gateway','authenticate · authorize','shield',35,70,'platform',3),service('policy','Policy enforcement','role · case · purpose','file',285,70,'platform',4),service('vault','Evidence vault','encrypt · retain','database',35,245,'platform',5),service('monitor','Security monitor','audit · detect · revoke','gauge',285,245,'platform',6),service('review','Qualified review','challenge · approve','user',18,115,'operation',7),service('fallback','Degraded mode','contain · continue','workflow',18,300,'operation',8)],edges:[edge('partner','gateway','signed'),edge('device','gateway','device trust'),edge('gateway','policy'),edge('policy','vault'),edge('policy','review','scoped'),edge('vault','review','evidence'),edge('monitor','policy','enforce',true),edge('review','fallback','fail safe')]};
  if(variant==='asset')return {nodes:[group('physical','PHYSICAL ASSET',25,50,260,450,'slate'),group('digital','LIFECYCLE CONTROL',340,25,500,510,'blue'),group('decision','ENGINEERING + SUPPLY',895,50,210,450,'green'),service('part','Serialized component','part · serial · position','boxes',28,80,'physical',1),service('custody','Custody event','receive · move · issue','package',28,260,'physical',2),service('install','Installation history','tail · position · exposure','plane',35,65,'digital',3),service('remove','Removal event','reason · evidence','wrench',280,65,'digital',4),service('shop','Shop finding','test · repair · modify','gauge',35,250,'digital',5),service('status','Technical status','life · condition · release','file',280,250,'digital',6),service('supply','Supply decision','stock · route · pool','network',18,110,'decision',7),service('reliability','Reliability review','repeat · outcome','history',18,300,'decision',8)],edges:[edge('part','install'),edge('custody','install'),edge('install','remove','operates'),edge('remove','shop'),edge('shop','status'),edge('status','supply'),edge('status','reliability'),edge('reliability','install','feedback',true)]};
  return {nodes:[group('observe','OBSERVE',20,65,245,410,'slate'),group('reason','ENGINEERING CONTROL LOOP',320,25,520,500,'blue'),group('govern','GOVERN',895,65,205,410,'green'),service('events','Fleet evidence','events · exposure','database',26,75,'observe',1),service('reports','Human reports','symptom · finding','user',26,245,'observe',2),service('case','Candidate case',domain,'search',35,65,'reason',3),service('analysis','Engineering analysis','hypothesis · counter-evidence','wrench',285,65,'reason',4),service('action','Corrective action','owner · due · scope','workflow',35,250,'reason',5),service('effect','Effectiveness review','recurrence · confidence','gauge',285,250,'reason',6),service('board','Reliability authority','accept · escalate','shield',18,105,'govern',7),service('program','Program change','task · interval · control','file',18,290,'govern',8)],edges:[edge('events','case'),edge('reports','case'),edge('case','analysis'),edge('analysis','board','evidence'),edge('board','action','authorized'),edge('action','effect'),edge('effect','program'),edge('effect','case','learn',true)]};
}

export function selectArchitectureVariant(domain:string,tags:string[],ata:string[]):Variant {const value=`${domain} ${tags.join(' ')}`.toLowerCase();if(ata.length||/(aircraft|engine|apu|hydraulic|pneumatic|fuel|electrical|navigation|fire|ice)/.test(value))return'aircraft';if(/(record|publication|document|logbook|task-card|work instruction)/.test(value))return'records';if(/(security|cyber|access|collaboration)/.test(value))return'security';if(/(part|rotable|inventory|material|component|supply|aog)/.test(value))return'asset';if(/(reliability|defect|outcome|program|rcm|msg-3|removal)/.test(value))return'reliability';return'cloud';}

export function ReferenceArchitecture({id,title,caption,domain,tags,ata}:{id:string;title:string;caption:string;domain:string;tags:string[];ata:string[]}){const variant=selectArchitectureVariant(domain,tags,ata);const graph=useMemo(()=>blueprint(variant,domain),[variant,domain]);return <figure className="reference-architecture" data-diagram-id={id} data-variant={variant}><header><span>REFERENCE ARCHITECTURE · {variant.toUpperCase()}</span><h3>{title}</h3><p>{caption}</p></header><div className="reference-flow"><ReactFlow nodes={graph.nodes} edges={graph.edges} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.08}} minZoom={.55} maxZoom={1.6} nodesDraggable={false} nodesConnectable={false} nodesFocusable={false} edgesFocusable={false} elementsSelectable={false} zoomOnScroll={false} panOnScroll={false} preventScrolling={false} panOnDrag={false} zoomOnDoubleClick={false} proOptions={{hideAttribution:true}}><Background color="#dbe3ea" gap={22} size={1}/><Controls showInteractive={false}/></ReactFlow></div><figcaption><span>INTERACTION</span> Page scrolling remains active over the figure. Use the visible controls to zoom or reset the view.</figcaption></figure>}
