export type VisualPlan = { compare:[string,string,string[]]; sequence:string[]; risks:[string,string,string][]; metrics:[string,string,string][]; states:string[] };

const plans: Record<string,VisualPlan> = {
  '2026-01-maintenance-decision-brief':{compare:['Chat transcript','Decision brief',['Source visibility','Uncertainty','Shift handover','Approval trace']],sequence:['Condition recorded','Evidence assembled','Conflicts exposed','Licensed review','Disposition logged'],risks:[['Fluent unsupported claim','High','Require cited evidence'],['Stale aircraft context','High','Freshness indicator'],['Automation bias','Medium','Authority boundary']],metrics:[['Evidence coverage','92%','target'],['Reviewer correction','< 8%','weekly'],['Handover time','−31%','observed']],states:['Draft evidence','Review ready','Under review','Dispositioned','Outcome linked']},
  '2026-02-event-driven-aircraft-telemetry':{compare:['Payload pipeline','Event custody',['Source preservation','Late arrival','Replay','Schema evolution']],sequence:['Aircraft records event','Edge stores envelope','Cloud acknowledges','Context resolves identity','Consumer checkpoints'],risks:[['Clock disagreement','High','Dual timestamps'],['Duplicate delivery','Medium','Idempotency key'],['Unknown tail mapping','High','Quarantine + repair']],metrics:[['Flight completeness','99.4%','SLO'],['Identity resolved','99.8%','SLO'],['Replay age','14 min','p95']],states:['Observed','Buffered','Accepted','Contextualized','Consumed']},
  '2026-03-chronic-defect-intelligence':{compare:['Keyword matches','Engineering cases',['Configuration context','Counter-evidence','Exposure','Review rationale']],sequence:['Event candidate','Identity join','Case hypothesis','Engineer challenge','Program action'],risks:[['False case join','High','Explain grouping'],['Exposure ignored','High','Rate normalization'],['Unknown shop result','Medium','Preserve unknown']],metrics:[['Case precision','87%','reviewed'],['Time assembled','−46%','median'],['Unknown outcomes','18%','backlog']],states:['Candidate','Correlated','Challenged','Confirmed','Governed']},
  '2026-04-maintenance-knowledge-retrieval':{compare:['Open semantic search','Controlled retrieval',['Effectivity','Revision state','Citations','Abstention']],sequence:['Question enriched','Eligibility filtered','Passages ranked','Claims cited','User verifies'],risks:[['Superseded source','Critical','Approval filter'],['Wrong effectivity','Critical','Tail constraint'],['Context split','High','Structure-aware chunks']],metrics:[['Citation precision','98%','gate'],['Valid abstention','94%','test'],['Stale documents','0','required']],states:['Ingested','Classified','Eligible','Retrieved','Verified']},
  '2026-08-maintenance-observability':{compare:['Platform monitoring','Decision observability',['Semantic health','Evidence freshness','Workflow delivery','Outcome trace']],sequence:['Signal deviates','Impact resolved','Owner notified','Decision path protected','Contract repaired'],risks:[['Green but incomplete','High','Decision SLO'],['Mapping drift','High','Semantic monitor'],['Alert without owner','Medium','Service ownership']],metrics:[['Evidence freshness','4 min','p95'],['Unresolved identity','0.3%','daily'],['Delivered in window','97.9%','SLO']],states:['Healthy','Degraded','Decision at risk','Contained','Recovered']},
  '2026-09-digital-work-package-orchestration':{compare:['Electronic bundle','Orchestrated package',['Readiness state','Change impact','Finding ownership','Closure lineage']],sequence:['Planning baselines','Materials confirm','Production executes','Engineering resolves','Records closes'],risks:[['Late task revision','High','Impact workflow'],['Offline conflict','High','Controlled sync'],['Finding orphaned','Critical','Named owner']],metrics:[['Ready at release','93%','weekly'],['Finding latency','−22%','median'],['Closure defects','0.7%','audit']],states:['Scoped','Planned','Ready','Active','Closed']},
  '2026-10-maintenance-ai-governance':{compare:['Policy review','Risk-tiered controls',['Use-case influence','Evidence burden','Release authority','Withdrawal path']],sequence:['Use case described','Influence classified','Evidence tested','Authority approves','Behavior monitored'],risks:[['Unmanaged tool','High','Accessible intake'],['Benchmark mismatch','High','Scenario evaluation'],['No fallback','Critical','Test withdrawal']],metrics:[['Inventory coverage','100%','required'],['Open limitations','7','tracked'],['Rollback test','< 15m','quarterly']],states:['Experimental','Assessed','Controlled pilot','Operational','Restricted']},
  '2026-11-maintenance-outcome-learning':{compare:['Proxy labels','Outcome chain',['Ambiguity','Revisions','Recurrence','Stewardship']],sequence:['Insight reviewed','Action executed','Finding captured','Outcome adjudicated','Learning approved'],risks:[['Removal=confirmed','High','Outcome chain'],['Unknown dropped','High','Explicit state'],['Self-label training','Critical','Independent review']],metrics:[['Outcome linked','84%','monthly'],['Inconclusive','13%','visible'],['Label revisions','6%','quarterly']],states:['Pending action','Observed','Inconclusive','Confirmed','Revised']},
  '2026-12-maintenance-intelligence-operating-system':{compare:['Use-case portfolio','Decision products',['Operational owner','Evidence contract','Outcome measure','Retirement rule']],sequence:['Decision selected','Evidence contracted','Product integrated','Outcome measured','Portfolio reviewed'],risks:[['Platform without owner','High','Domain product team'],['Pilot never operated','High','Service readiness'],['Shadow record','Critical','System boundary']],metrics:[['Trace complete','96%','portfolio'],['Products adopted','8 / 11','quarterly'],['Retired safely','3','year']],states:['Proposed','Incubating','Operational','Scaling','Retired']}
};

const defaultPlan:VisualPlan={compare:['Fragmented workflow','Evidence-led workflow',['Traceability','Decision latency','Human authority','Outcome learning']],sequence:['Evidence arrives','Context assembled','Assessment formed','Human reviews','Outcome returns'],risks:[['Missing context','High','Evidence gate'],['Unsupported inference','High','Citation'],['Unowned action','Critical','Named authority']],metrics:[['Evidence linked','95%','target'],['Review latency','−28%','median'],['Outcome captured','82%','monthly']],states:['Observed','Assembled','Assessed','Reviewed','Learned']};

function Frame({label,title,children}:{label:string;title:string;children:React.ReactNode}){return <figure className="whitepaper-figure"><header><span>{label}</span><h3>{title}</h3></header>{children}</figure>}

export function ComparisonMatrix({plan}:{plan:VisualPlan}){const [before,after,rows]=plan.compare;return <Frame label="Operating comparison" title={`${before} versus ${after}`}><div className="comparison-matrix"><div/><strong>{before}</strong><strong>{after}</strong>{rows.map((row,i)=><div className="matrix-row" key={row}><b>{row}</b><span className="weak">{['Implicit','Manual','Fragmented','Variable'][i%4]}</span><span className="strong">{['Visible','Controlled','Connected','Measured'][i%4]}</span></div>)}</div><figcaption>The proposed design improves inspectability and control; it does not remove professional judgment.</figcaption></Frame>}

export function OperationalSequence({plan}:{plan:VisualPlan}){return <Frame label="Operational sequence" title="Evidence and authority over time"><div className="sequence-visual"><div className="sequence-lanes"><span>System</span><span>Domain logic</span><span>Qualified role</span></div>{plan.sequence.map((step,i)=><div className={`sequence-event lane-${i%3}`} key={step}><i>{String(i+1).padStart(2,'0')}</i><b>{step}</b><span>{i<4?'handoff ↓':'recorded outcome'}</span></div>)}</div><figcaption>Vertical placement identifies who or what owns each step; the sequence makes handoffs and authority explicit.</figcaption></Frame>}

export function RiskRegister({plan}:{plan:VisualPlan}){return <Frame label="Failure analysis" title="Failure modes, consequence, and engineered control"><div className="risk-register"><div className="risk-head"><span>Failure mode</span><span>Exposure</span><span>Control</span></div>{plan.risks.map(([risk,level,control])=><div className="risk-row" key={risk}><strong>{risk}</strong><span className={`risk-${level.toLowerCase()}`}>{level}</span><span>{control}</span></div>)}</div><figcaption>Controls are attached to observable failure modes rather than listed as generic principles.</figcaption></Frame>}

export function EvidenceDashboard({plan}:{plan:VisualPlan}){return <Frame label="Measurement model" title="Signals that show whether the design works"><div className="metric-grid">{plan.metrics.map(([label,value,note])=><div className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small><div className="metric-spark"><i/><i/><i/><i/><i/></div></div>)}</div><figcaption>Illustrative operating measures define the shape of useful evidence; they are not claims about a specific airline.</figcaption></Frame>}

export function StateModel({plan}:{plan:VisualPlan}){return <Frame label="Lifecycle model" title="Controlled states and transition evidence"><div className="state-model">{plan.states.map((state,i)=><div key={state}><span>{i+1}</span><strong>{state}</strong>{i<plan.states.length-1?<i>→</i>:null}</div>)}</div><figcaption>Named states prevent workflow progress from being inferred from scattered messages or incomplete transactions.</figcaption></Frame>}

export function ArticleVisual({slug,index,plan:providedPlan}:{slug:string;index:0|1|2;plan?:VisualPlan}){const plan=providedPlan||plans[slug]||defaultPlan;const order=Math.abs([...slug].reduce((n,c)=>n+c.charCodeAt(0),0))%3;if(index===0)return order===0?<ComparisonMatrix plan={plan}/>:order===1?<OperationalSequence plan={plan}/>:<StateModel plan={plan}/>;if(index===1)return order===0?<OperationalSequence plan={plan}/>:order===1?<RiskRegister plan={plan}/>:<EvidenceDashboard plan={plan}/>;return order===0?<RiskRegister plan={plan}/>:order===1?<EvidenceDashboard plan={plan}/>:<ComparisonMatrix plan={plan}/>}
