import type { Metadata } from 'next';
import { ArticleShell } from '../../components/ArticleShell';
import { ExecutiveSummary, KeyTakeaways, ReferenceList } from '../../components/Publication';
import type { ArticleRecord } from '../../lib/articles';

const article: ArticleRecord={id:'nbl-2026-09-18',title:'A Reliability Alert Is Only Useful If It Arrives in the Decision Window',slug:'2026-09-reliability-alert-latency',issueDate:'2026-09-18',publishedAt:'2026-09-18T19:00:00-05:00',updatedAt:'2026-09-18T19:00:00-05:00',summary:'A practical architecture for measuring whether aircraft reliability signals arrive early enough, with enough evidence, to support the maintenance decision they were designed for.',description:'How airline engineering teams can design reliability alerts around decision windows, evidence freshness, event time, replay, and human review instead of optimizing only model accuracy.',categories:['Reliability Engineering','Aircraft Data'],topicTags:['Decision latency','Reliability alerts','Aircraft telemetry'],ataChapters:[],articleType:'Engineering Guide',estimatedReadingTime:10,publicationStatus:'published',featuredStatus:'featured',diagramIdentifiers:['reliability-decision-window'],referenceCount:5,relatedArticleSlugs:['2026-08-exposure-normalized-reliability','2026-09-telemetry-time-integrity'],previousArticleSlug:'2026-09-maintenance-event-contracts',nextArticleSlug:null};

export const metadata:Metadata={title:article.title,description:article.description,alternates:{canonical:`/articles/${article.slug}`}};

const flow=`AIRCRAFT / MRO / OPS EVIDENCE\n telemetry · faults · removals · flight context\n                 |\n                 v\n        Event-time integrity gate\n   identity · effectivity · provenance\n                 |\n                 v\n      Reliability signal builder\n exposure · rules · model · confidence\n                 |\n        +--------+---------+\n        |                  |\n   fresh enough?      late / incomplete\n        |                  |\n        v                  v\n Decision-window       quarantine / replay\n classification             |\n        |                    +----> recompute\n        v\n Evidence package + alert\n        |\n        v\n Qualified engineering / maintenance review\n        |\n        v\n disposition + outcome feedback`;

export default function Page(){return <ArticleShell article={article}>
<ExecutiveSummary><p>Airline reliability teams can build an accurate anomaly detector and still deliver a poor operational product. The missing variable is often time: did the signal arrive while somebody could still make the decision it was intended to support?</p><p>This article proposes treating decision latency as an explicit reliability-product requirement. The architecture measures evidence age from aircraft event time, separates processing latency from source delay, classifies signals against a defined decision window, and keeps late evidence available for replay and learning rather than quietly presenting stale insight as current.</p></ExecutiveSummary>
<section><h2>1. Model accuracy is not operational usefulness</h2><p>A reliability signal has at least three qualities: whether it is technically credible, whether its evidence is sufficiently complete, and whether it arrives in time for the intended workflow. A high-confidence prediction delivered after an aircraft has departed, a work package has closed, or the relevant planning cutoff has passed may still be useful for engineering analysis, but it is no longer the same operational product.</p><p>That distinction should be designed into the system instead of left to dashboard users to infer from timestamps.</p></section>
<section><h2>2. Define the decision window before the alert</h2><p>Start with the decision, not the model. Identify the consumer, the action the signal is meant to inform, the earliest useful evidence point, and the latest point at which the signal can still influence that workflow. Different use cases legitimately have different windows. A fleet-trend review can tolerate latency that would make a same-day maintenance-planning alert useless.</p><p>Do not encode one universal SLA and call the problem solved. The useful unit is a decision-window policy attached to the signal type and operational context.</p></section>
<section><h2>3. Measure latency from event time</h2><p>Cloud processing time alone is misleading. Aircraft data can be buffered, transmitted intermittently, or offloaded at the gate. AWS's connected-aircraft reference architecture explicitly describes both near-real-time events and flight-data offload to Amazon S3 at the gate. Its aircraft predictive-maintenance architecture also notes that QAR upload frequency varies with installed connectivity capability.</p><p>For each evidence item, preserve at least source event time and ingestion time. Then decompose end-to-end latency into source/connectivity delay, ingestion delay, processing delay, correlation delay, and alert-delivery delay. This makes a late alert diagnosable rather than merely late.</p></section>
<section><h2>4. Reference architecture</h2><p>This original Northbound Labs flow treats freshness as part of evidence quality and preserves a separate path for late or incomplete evidence.</p><pre aria-label="Reliability alert decision-window architecture"><code>{flow}</code></pre><p>On AWS, an event bus can decouple producers and consumers, while queues can isolate consumer retry and back-pressure. Raw evidence can be retained durably for replay. Consumers should be idempotent because retries and replay can deliver the same logical event more than once. AWS guidance explicitly recommends idempotent event processing for this reason.</p></section>
<section><h2>5. Make freshness visible in the evidence package</h2><p>An alert should carry more than a score. Include the observation window, newest and oldest evidence times, data-completeness state, aircraft/configuration identity, rule or model version, signal-generation time, decision-window status, and links to authoritative source records where permitted.</p><p>A useful state model is <strong>within-window</strong>, <strong>degraded</strong>, <strong>expired-for-action</strong>, and <strong>retrospective-only</strong>. Those labels describe product fitness, not aircraft airworthiness and not maintenance authority.</p></section>
<section><h2>6. Late data should change history carefully</h2><p>Late evidence creates a governance question: should an already-issued signal be recomputed? For analytical products, often yes, provided the system preserves both the original decision-time view and the later reconstructed view. Rewriting history in place destroys the ability to explain what a user actually knew when a decision was made.</p><p>Store immutable source evidence, version derived projections, and record why a recomputation occurred. Replay should reproduce a new analytical state without pretending the earlier state never existed.</p></section>
<section><h2>7. Reliability programs need review, not autonomous alert authority</h2><p>FAA AC 120-17B describes reliability programs as mechanisms for monitoring performance and effectiveness and calls for continuing evaluation and documented review. That supports disciplined measurement and review; it does not turn a cloud-generated alert into approved maintenance data or an autonomous maintenance decision.</p><p>Keep analytical prioritization separate from approved maintenance instructions, required records, and qualified disposition. An AI service may summarize the evidence package or help rank cases, but its output should retain provenance, freshness, uncertainty, and a clear human-review boundary.</p></section>
<section><h2>8. Operate the product with latency SLOs</h2><p>Track the percentage of signals delivered within their decision window, p50/p95 evidence age, late-evidence rate, incomplete-context rate, duplicate/replay rate, alert acknowledgement time, and the fraction of alerts that were already expired when first viewed. Segment these measures by fleet, station, connectivity path, signal family, and source system before blaming the model.</p><p>For a pilot, choose one signal family and one operational decision. Run it in shadow mode, reconstruct several weeks of event-time behavior, and compare decision-window performance with model-quality metrics. If the signal is accurate but routinely late, improve the data path before tuning another decimal place of model performance.</p></section>
<KeyTakeaways><ul><li>Define the operational decision window before designing the reliability alert.</li><li>Measure freshness from aircraft/source event time, not only cloud processing time.</li><li>Separate late evidence from bad evidence; preserve it for controlled replay and learning.</li><li>Version analytical history so reconstructed results do not erase what was known at decision time.</li><li>Keep alerts and AI as decision support, with authoritative maintenance data and qualified human review remaining distinct.</li></ul></KeyTakeaways>
<section><h2>Editorial note</h2><p>This is an independent engineering reference architecture, not FAA-approved maintenance data, an operator maintenance-program procedure, or instructions for continued airworthiness. Service selections are illustrative. Any production implementation should be evaluated against the operator's approved programs, cybersecurity controls, data governance, operational procedures, and applicable regulatory obligations.</p></section>
<ReferenceList><li><a href="https://www.faa.gov/regulations_policies/advisory_circulars/index.cfm/go/document.information/documentid/1035253">FAA AC 120-17B — Reliability Program Methods—Standards for Determining Time Limitations</a></li><li><a href="https://docs.aws.amazon.com/reference-architecture-diagrams/latest/connected-aircraft-solution-architecture/connected-aircraft-solution-architecture.html">AWS — Connected Aircraft Solution Architecture</a></li><li><a href="https://docs.aws.amazon.com/reference-architecture-diagrams/latest/aircraft-predictive-maintenance/aircraft-predictive-maintenance.html">AWS — Aircraft Predictive Maintenance</a></li><li><a href="https://docs.aws.amazon.com/eventbridge/latest/ref/welcome.html">Amazon EventBridge — Events Reference</a></li><li><a href="https://aws.amazon.com/blogs/compute/operating-lambda-design-principles-in-event-driven-architectures-part-2/">AWS Compute Blog — Design principles in event-driven architectures</a></li></ReferenceList>
</ArticleShell>}
