import { AlertTriangle, Archive, Bot, CircleCheck, Database, FileCheck2, Gauge, Plane, RadioTower, RotateCcw, ShieldCheck, UserCheck, Wrench } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { VisualFrame, short } from '../Frame';
import type { FamilyProps } from '../types';

const labels=(props:FamilyProps)=>[...props.tags,'Evidence','Qualified review','Outcome'].slice(0,5);
const disclosure='Illustrative structure—labels and values must be validated against the operating context.';

export function PremiumArchitecture(props:FamilyProps){const stages=[['Operational evidence','Aircraft events','Enterprise records'],['Context platform','Identity + effectivity','Evidence custody'],['Decision services','Bounded analysis','Workflow orchestration'],['Authority + record','Qualified review','System of record']];return <VisualFrame family="architecture" props={props} caption="Boundaries separate evidence custody, contextual services, decision support, and accountable maintenance action."><div className="pr-architecture"><aside><b>CONTROL PLANE</b><span>Identity</span><span>Lineage</span><span>Observability</span><span>Security</span></aside><main>{stages.map(([stage,a,b],i)=><section key={stage}><header><span>0{i+1}</span><b>{stage}</b></header><div><article><Database/><b>{a}</b><small>{i===0?short(props.domain):labels(props)[i]}</small></article><i>→</i><article><ShieldCheck/><b>{b}</b><small>{['source truth','versioned context','explicit limits','recorded disposition'][i]}</small></article></div></section>)}</main><div className="pr-authority"><UserCheck/><b>Human authority boundary</b><span>inspect · challenge · decide · record</span></div></div></VisualFrame>}

export function PremiumTopology(props:FamilyProps){const nodes=[['Source','aircraft / enterprise'],['Gateway','authenticated handoff'],['Context','identity + effectivity'],['Service',short(props.domain,22)],['Operation','qualified action']];return <VisualFrame family="topology" props={props} caption="The topology identifies physical and logical handoffs, evidence custody, and the point where operational authority begins."><div className="pr-topology"><div className="pr-topology-zones"><span>OPERATIONAL EDGE</span><span>TRUSTED PLATFORM</span><span>MAINTENANCE OPERATION</span></div><div className="pr-topology-path">{nodes.map(([name,note],i)=><article key={name} data-zone={i<2?'edge':i<4?'platform':'operation'}><span>{String(i+1).padStart(2,'0')}</span>{i===0?<Plane/>:i===1?<RadioTower/>:i===4?<Wrench/>:<Database/>}<b>{name}</b><small>{note}</small>{i<nodes.length-1?<i>→</i>:null}</article>)}</div><div className="pr-topology-flows"><b>Evidence path</b><span>source envelope</span><span>canonical context</span><span>decision brief</span><span>recorded outcome</span></div></div></VisualFrame>}

export function PremiumDashboard(props:FamilyProps){const cards=[['Evidence completeness','94%'],['Cases awaiting review','18'],['Decision window','27m'],['Outcome linkage','98.6%']];return <VisualFrame family="dashboard" props={props} caption={`${disclosure} The operating view keeps evidence health, workload, latency, and outcome traceability separate.`}><div className="pr-dashboard"><header>ILLUSTRATIVE OPERATING VIEW · {short(props.domain,55)}</header><div className="pr-dashboard-kpis">{cards.map(([name,value],i)=><article key={name}><small>{name}</small><b>{value}</b><i style={{width:`${58+i*10}%`}}/></article>)}</div><div className="pr-dashboard-main"><section><h4>Decision-path health</h4>{labels(props).map((label,i)=><div className="pr-health-row" key={label}><span data-state={i===2?'watch':'ready'}/><b>{label}</b><small>{i===2?'review':'ready'}</small></div>)}</section><section><h4>Case arrival and completion</h4><div className="pr-spark-bars">{[28,43,38,56,49,67,61,76,64,81,74,88].map((v,i)=><i style={{height:`${v}%`}} key={i}/>)}</div><div className="pr-chart-key"><span>arrivals</span><span>completed</span><span>review threshold</span></div></section><aside><h4>Attention</h4><AlertTriangle/><b>Evidence gap</b><p>Inspect the oldest unresolved identity before increasing automation.</p></aside></div></div></VisualFrame>}

export function PremiumTimeline(props:FamilyProps){const items=['Baseline evidence','Applicability resolved','Work released','Finding reviewed','Outcome recorded'];return <VisualFrame family="timeline" props={props} caption="The evidence timeline exposes prerequisites, authority gates, and feedback rather than implying that maintenance work is a simple linear process."><div className="pr-timeline"><div className="pr-time-axis"><span>T0</span><span>DECISION WINDOW</span><span>OUTCOME WINDOW</span></div>{items.map((item,i)=><article key={item}><span>{String(i+1).padStart(2,'0')}</span><div><b>{item}</b><small>{i===0?short(props.domain,42):labels(props)[i-1]}</small></div><i style={{width:`${24+i*15}%`}}/>{i===1||i===3?<em>{i===1?'APPLICABILITY GATE':'QUALIFIED REVIEW'}</em>:null}</article>)}<aside><RotateCcw/><b>New evidence reopens the case</b><span>prior decisions remain part of the trace</span></aside></div></VisualFrame>}

export function PremiumDecisionTree(props:FamilyProps){return <VisualFrame family="decision-tree" props={props} caption="Explicit branches preserve repair, abstention, and escalation as valid outcomes when evidence or authority is insufficient."><div className="pr-tree"><div className="pr-tree-root"><ShieldCheck/><b>Evidence applicable and current?</b></div><div className="pr-tree-branch yes">YES</div><div className="pr-tree-branch no">NO</div><div className="pr-tree-node assess"><b>Assess within boundary</b><small>{short(props.domain,38)}</small></div><div className="pr-tree-node repair"><b>Repair evidence context</b><small>identity · effectivity · revision</small></div><div className="pr-tree-node review"><UserCheck/><b>Qualified review</b><small>accept · modify · reject</small></div><div className="pr-tree-node stop"><AlertTriangle/><b>Abstain or escalate</b><small>outside approved boundary</small></div><footer>Software structures the decision. Approved data and qualified personnel retain authority.</footer></div></VisualFrame>}

export function PremiumHeatmap(props:FamilyProps){const rows=labels(props).slice(0,4);return <VisualFrame family="heatmap" props={props} caption={`${disclosure} Cohort structure makes concentration and missing evidence visible without collapsing them into one fleet average.`}><div className="pr-heatmap"><header><span>COHORT VIEW</span><b>{short(props.domain,54)}</b></header><div className="pr-heatmap-grid"><i/>{['Fleet A','Fleet B','Fleet C','Fleet D','Fleet E'].map(x=><b key={x}>{x}</b>)}{rows.map((row,r)=><div className="pr-heat-row" key={row}><strong>{row}</strong>{[0,1,2,3,4].map(c=><i key={c} data-level={(r*2+c*3+props.slug.length)%5}><small>{r===0&&c===4?'review':''}</small></i>)}</div>)}</div><aside><span><i data-level="1"/>Lower concentration</span><span><i data-level="3"/>Review cohort</span><span><i data-level="4"/>Priority cohort</span></aside></div></VisualFrame>}

export function PremiumBlueprint(props:FamilyProps){const lanes=[['Operator','Observe','Review evidence','Select disposition','Confirm record'],['Interface','Signal','Decision brief','Authority gate','Outcome receipt'],['Services','Resolve context','Assemble case','Route decision','Publish event'],['Evidence','Source envelope','Configuration','Approved basis','Immutable trace']];return <VisualFrame family="service-blueprint" props={props} caption="The blueprint aligns frontstage work, backstage services, evidence systems, and authority across one maintenance decision."><div className="pr-blueprint"><header><b>ROLE / SYSTEM</b>{['Detect','Understand','Decide','Learn'].map(x=><span key={x}>{x}</span>)}</header>{lanes.map(([lane,...steps],li)=><section key={lane} data-lane={li}><b>{lane}</b>{steps.map((step,i)=><article key={step}><span>{step}</span>{(li===0&&i===2)||(li===3&&i===2)?<UserCheck/>:null}</article>)}</section>)}<footer><b>LINE OF AUTHORITY</b><span>{short(props.domain,60)} · explicit handoff to qualified personnel</span></footer></div></VisualFrame>}

export function PremiumJourney(props:FamilyProps){const steps=['Detect','Orient','Coordinate','Act','Learn'];return <VisualFrame family="journey-map" props={props} caption="The journey shows operational confidence and friction around the maintenance handoff, not merely backend transactions."><div className="pr-journey"><header><span>OPERATOR JOURNEY</span><b>{short(props.domain,55)}</b></header><div className="pr-journey-curve">{steps.map((step,i)=><article key={step} style={{'--level':`${[62,34,72,42,24][i]}%`} as React.CSSProperties}><i/><b>{step}</b><small>{['signal arrives','context assembled','ownership aligned','authority exercised','outcome captured'][i]}</small></article>)}</div><div className="pr-journey-notes"><span><AlertTriangle/>Friction: missing or conflicting evidence</span><span><UserCheck/>Critical moment: accountable authority handoff</span><span><RotateCcw/>Learning: confirmed outcome changes the next case</span></div></div></VisualFrame>}

export function PremiumKnowledge(props:FamilyProps){const nodes=['Aircraft','Position','Component',labels(props)[0],'Task','Document','Finding'];return <VisualFrame family="knowledge-graph" props={props} caption="Governed identities and effective-dated relationships connect evidence while recorded facts remain distinguishable from inferred links."><div className="pr-knowledge"><header><span>GOVERNED EVIDENCE GRAPH</span><b>{short(props.domain,58)}</b></header><svg viewBox="0 0 1000 430" role="img" aria-label={`Governed evidence relationships for ${props.domain}`}><g className="pr-graph-lines">{[[500,210,170,90],[500,210,380,65],[500,210,700,80],[500,210,830,210],[500,210,690,355],[500,210,360,360]].map((p,i)=><path d={`M${p[0]} ${p[1]} L${p[2]} ${p[3]}`} key={i}/>)}</g>{[[500,210],[170,90],[380,65],[700,80],[830,210],[690,355],[360,360]].map(([x,y],i)=><g className="pr-graph-node" data-root={i===0||undefined} transform={`translate(${x} ${y})`} key={nodes[i]}><circle r={i===0?62:48}/><text y="-2">{nodes[i]}</text><text className="relation" y="17">{i===0?'identity root':['installed at','applies to','generated','addresses','supports','confirmed by'][i-1]}</text></g>)}</svg><aside><span>— recorded relationship</span><span>○ effective-dated identity</span><span>Inferences must retain source and confidence</span></aside></div></VisualFrame>}

export function PremiumAircraft(props:FamilyProps){const ata=props.ata[0]||'SYS';return <VisualFrame family="aircraft" props={props} caption="The functional view anchors evidence in aircraft installation, configuration, energy or signal flow, and maintenance interpretation."><div className="pr-aircraft"><header><span>FUNCTIONAL SYSTEM VIEW · ATA {ata}</span><b>{short(props.domain,55)}</b></header><div className="pr-aircraft-boundary"><article><Gauge/><b>Sensing</b><small>condition · validity</small></article><i>signal →</i><article><Database/><b>Control function</b><small>mode · command · state</small></article><i>response →</i><article><Wrench/><b>Physical system</b><small>energy · actuation · load</small></article><i>event →</i><article><FileCheck2/><b>Maintenance evidence</b><small>message · test · finding</small></article></div><div className="pr-aircraft-context"><Plane/><span><b>Effectivity</b> tail · position · modification</span><span><b>Operating regime</b> phase · demand · environment</span><span><b>Authority</b> approved aircraft data</span></div></div></VisualFrame>}

export function PremiumMetrics(props:FamilyProps){return <VisualFrame family="metrics" props={props} caption={`${disclosure} Distribution, exposure, threshold, and sample sufficiency are shown together so an average cannot masquerade as a decision.`}><div className="pr-metrics"><header><span>ILLUSTRATIVE RELIABILITY ANALYSIS</span><b>{short(props.domain,55)}</b></header><section className="pr-distribution"><div className="pr-bars">{[8,14,23,37,55,73,89,96,84,67,48,32,19,11].map((v,i)=><i style={{height:`${v}%`}} key={i}/>)}</div><span className="pr-limit">review threshold</span><footer><span>lower</span><span>observed condition</span><span>higher</span></footer></section><aside><div><small>Exposure basis</small><b>Flight hours / cycles</b></div><div><small>Uncertainty</small><b>90% interval shown</b></div><div><small>Sample status</small><b>Review, not automation</b></div></aside></div></VisualFrame>}

export function PremiumInfographic(props:FamilyProps){const cards:[LucideIcon,string,string,string][]=[[CircleCheck,'Recorded fact','Preserve','source identity · event time'],[Gauge,'Derived signal','Qualify','method · version · applicability'],[Bot,'Generated synthesis','Cite','claim-level evidence · uncertainty'],[AlertTriangle,'Unsupported claim','Reject','abstain · repair · escalate']];return <VisualFrame family="infographic" props={props} caption="The evidence taxonomy assigns a distinct treatment to recorded facts, derived signals, generated synthesis, and unsupported claims."><div className="pr-infographic"><header><span>EVIDENCE TREATMENT MODEL</span><b>{short(props.domain,58)}</b></header><div>{cards.map(([Icon,title,action,note],i)=><article key={title}><span>0{i+1}</span><Icon/><b>{title}</b><em>{action}</em><small>{note}</small></article>)}</div><footer>Fluency, confidence, or visual polish never upgrades a claim’s authority.</footer></div></VisualFrame>}

export function PremiumRisk(props:FamilyProps){return <VisualFrame family="risk" props={props} caption="The control view separates consequence, likelihood, and uncertainty; the highest-risk region requires explicit authority and evidence controls."><div className="pr-risk"><header><span>CONTROL DECISION · RISK</span><b>{short(props.domain,55)}</b></header><section><div className="pr-risk-matrix"><span className="pr-y">Consequence</span><div>{Array.from({length:16},(_,i)=><i data-risk={3-Math.floor(i/4)+i%4} key={i}/>)}</div><span className="pr-x">Likelihood</span></div><aside>{[['Monitor','routine observation'],['Control','engineered guardrail'],['Escalate','qualified review'],['Stop','outside authority']].map(([a,n],i)=><article key={a} data-risk={i}><span/><div><b>{a}</b><small>{n}</small></div></article>)}</aside></section><footer><ShieldCheck/><span>Uncertainty remains a separate reason to repair evidence or abstain.</span></footer></div></VisualFrame>}

export function PremiumTable(props:FamilyProps){const rows=[['Recorded evidence','Source identity · lineage','Retain'],['Normalized context','Mapping · effectivity','Review'],['Analytical output','Method · applicability','Bound'],['Operational decision','Qualified role · basis','Record']];return <VisualFrame family="table" props={props} caption="The engineering control table makes ownership, required evidence, and treatment directly comparable."><div className="pr-table"><header><span>CONTROL REGISTER</span><b>{short(props.domain,58)}</b></header><div className="pr-table-grid"><b>Information class</b><b>Required control</b><b>Treatment</b>{rows.flatMap(row=>row.map(cell=><span key={`${row[0]}-${cell}`}>{cell}</span>))}</div><footer><Archive/><span>Corrections append to the trace; they do not erase the evidence used for an earlier decision.</span></footer></div></VisualFrame>}
