import { archiveYears, articles, formatIssue } from './lib/articles';

const topics = [
  { index: '01', slug:'maintenance-operations', title: 'Maintenance Operations', copy: 'Control, planning, work packages, task execution, records, materials, and operational recovery.', keywords:/maintenance control|work package|task card|planning|mro|records|parts/i },
  { index: '02', slug:'aircraft-systems', title: 'Aircraft Systems', copy: 'ATA systems, aircraft health messages, telemetry, fault isolation, and installed configuration.', keywords:/aircraft|apu|ata|telemetry|fault message|landing gear|pneumatic|fuel|electrical/i },
  { index: '03', slug:'reliability', title: 'Reliability Engineering', copy: 'Repeat defects, component performance, chronic cases, exposure, findings, and program effectiveness.', keywords:/reliability|repeat defect|chronic|removal|failure|condition monitoring/i },
  { index: '04', slug:'ai-automation', title: 'AI & Automation', copy: 'Decision support, machine learning, copilots, computer vision, agents, and appropriate abstention.', keywords:/\bai\b|machine learning|copilot|computer vision|agent|model|predictive/i },
  { index: '05', slug:'data-cloud', title: 'Data & Cloud Architecture', copy: 'AWS patterns, event-driven systems, governed data products, integration, and observability.', keywords:/cloud|aws|event-driven|api|data|integration|observability|stream/i },
  { index: '06', slug:'governance', title: 'Safety, Governance & Human Factors', copy: 'Authority boundaries, assurance evidence, cybersecurity, human review, and accountable release.', keywords:/governance|assurance|authority|human factors|security|safety|risk/i }
];
const months = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];

export default function HomePage() {
  const latest = articles[0];
  const topicEntries=topics.map(topic=>{const matches=articles.filter(article=>topic.keywords.test(`${article.title} ${article.summary} ${article.topicTags.join(' ')}`));return{...topic,count:matches.length,latest:matches[0]||latest}});
  return <main>
    <nav className="masthead"><a className="brand" href="#top" aria-label="Northbound Labs home"><span className="brand-mark">N</span><span>NORTHBOUND LABS</span></a><div className="edition">Independent aviation maintenance, MRO & AI journal · Est. 2026</div><div className="navlinks"><a href={`/articles/${latest.slug}`}>Latest</a><a href="#research">Topics</a><a href="#publications">Archive</a><a href="#about">About</a></div></nav>
    <div className="layout" id="top"><div className="main-column">
      <section className="hero"><div className="issue-line"><span>INDEPENDENT TECHNICAL JOURNAL</span><span>CURRENT · {formatIssue(latest.issueDate).toUpperCase()}</span></div><nav className="hero-topics" aria-label="Latest article by research domain">{topicEntries.map(topic=><a href={`/articles/${topic.latest.slug}`} title={`Latest in ${topic.title}: ${topic.latest.title}`} key={topic.slug}>{topic.title}<span>↗</span></a>)}</nav><h1>Engineering better aircraft maintenance decisions.</h1><div className="hero-bottom"><p className="lead">Technical analysis for the people designing, governing, and operating modern MRO systems.</p><a className="text-link" href="#research">Explore topics <span>↓</span></a></div><a className="latest-feature" href={`/articles/${latest.slug}`}><div><span>Latest issue · {formatIssue(latest.issueDate)}</span><h2>{latest.title}</h2><p>{latest.description}</p></div><div className="latest-action"><span>{latest.estimatedReadingTime} min read</span><strong>Read latest →</strong></div></a></section>
      <section id="research" className="research-index" aria-labelledby="research-title"><header className="section-header"><span>Research domains</span><div><h2 id="research-title">Choose a technical focus</h2><p>Browse by the operating problem, engineering discipline, or control boundary you are working on.</p></div></header><div className="topic-list">{topicEntries.map((topic) => <a className="topic-row" id={`topic-${topic.slug}`} href={`/articles/${topic.latest.slug}`} key={topic.title}><span className="topic-index">{topic.index}</span><h3>{topic.title}</h3><p>{topic.copy}</p><span className="topic-count">{topic.count} articles</span><span className="topic-arrow">↗</span></a>)}</div></section>
      <section id="publications" className="publications" aria-labelledby="archive-title"><header className="section-header archive-header"><span>Publication log</span><div><h2 id="archive-title">The aviation maintenance archive</h2><p>Issue dates organize the editorial archive, including supplemental AI and maintenance-engineering editions published within selected months.</p></div></header><div className="publication-list">{articles.map((item, index) => <a className="publication" href={`/articles/${item.slug}`} key={item.slug}><div className="publication-number">{String(index + 1).padStart(3, '0')}</div><div className="publication-date">{formatIssue(item.issueDate)}</div><div className="publication-copy"><div className="publication-meta"><span>{item.articleType}</span><span>{item.estimatedReadingTime} min</span></div><h3>{item.title}</h3><p>{item.summary}</p></div><span className="publication-arrow">↗</span></a>)}</div></section>
    </div><aside className="year-rail" aria-label="Archive by year"><div className="rail-sticky"><div className="rail-label">Browse by year</div><p className="rail-note">Select a year to reveal its monthly issues.</p><div className="year-list">{archiveYears.map(({ year, articles: yearArticles }) => <details key={year}><summary><span>{year}</span><span>{yearArticles.length ? `${yearArticles.length} ${yearArticles.length === 1 ? 'issue' : 'issues'}` : 'Planned'}</span></summary><div className="month-grid">{months.map((month, index) => { const monthArticles=yearArticles.filter((item)=>Number(item.issueDate.slice(5,7))===index+1);const article=monthArticles.find((item)=>item.issueDate.endsWith('-01'))||monthArticles[0]; return article ? <a className="month-link active-month" href={`/articles/${article.slug}`} title={`${monthArticles.length} ${monthArticles.length===1?'issue':'issues'} in ${month} ${year}`} key={month}>{month}{monthArticles.length>1?<sup>{monthArticles.length}</sup>:null}</a> : <span className="month-pending" aria-disabled="true" title={`${month} ${year} is not yet published`} key={month}>{month}</span>; })}</div></details>)}</div><a className="rail-all" href="#publications">View all {articles.length} issues ↓</a></div></aside></div>
    <footer id="about" className="site-footer"><div><span className="brand-mark small">N</span> Northbound Labs</div><p>Independent research on aviation maintenance, MRO modernization, applied AI, aircraft systems, and the technology connecting operational evidence to human decisions.</p><div><a href="/feed.xml">RSS</a> · <a href="/sitemap.xml">Sitemap</a></div></footer>
  </main>;
}
