import { archiveYears, articles, formatIssue } from './lib/articles';

const topics = [
  { index: '01', title: 'AI for Maintenance Operations', copy: 'Evidence-grounded copilots, alert triage, chronic-defect analysis, predictive maintenance, and human-review safeguards.' },
  { index: '02', title: 'MRO & Work Management', copy: 'Work orders, task cards, digital work packages, planning, records, parts, technician workflows, and legacy-system renewal.' },
  { index: '03', title: 'Aircraft Systems & Reliability', copy: 'ATA chapters, aircraft health messages, alerts, repeat defects, component reliability, telemetry, and fleet engineering.' },
  { index: '04', title: 'Aviation Data & Cloud Architecture', copy: 'Event-driven platforms, AWS architectures, governed data products, system integration, observability, and resilient operations.' }
];
const months = ['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];

export default function HomePage() {
  const latest = articles[0];
  return <main>
    <nav className="masthead"><a className="brand" href="#top" aria-label="Northbound Labs home"><span className="brand-mark">N</span><span>NORTHBOUND LABS</span></a><div className="edition">Independent aviation maintenance, MRO & AI journal · Est. 2026</div><div className="navlinks"><a href="#research">Research</a><a href="#publications">Archive</a><a href="#about">About</a></div></nav>
    <div className="layout" id="top"><div className="main-column">
      <section className="hero"><div className="issue-line"><span>{articles.length} PUBLISHED ISSUES</span><span>CURRENT · {formatIssue(latest.issueDate).toUpperCase()}</span></div><p className="eyebrow">Aviation maintenance · MRO modernization · Applied AI · Reliability engineering</p><h1>Modernizing the systems behind aircraft maintenance.</h1><div className="hero-bottom"><p className="lead">Northbound Labs examines how modern MRO platforms, aircraft telemetry, reliability engineering, AI, and cloud architecture can improve maintenance decisions while preserving traceability and qualified human review.</p><a className="text-link" href="#publications">Open the archive <span>↘</span></a></div></section>
      <section id="research" className="research-index" aria-labelledby="research-title"><header className="section-header"><span>Research desk</span><h2 id="research-title">Four operating domains</h2></header><div className="topic-list">{topics.map((topic) => <article className="topic-row" key={topic.title}><span className="topic-index">{topic.index}</span><h3>{topic.title}</h3><p>{topic.copy}</p><span className="topic-arrow">↗</span></article>)}</div></section>
      <section id="publications" className="publications" aria-labelledby="archive-title"><header className="section-header archive-header"><span>Publication log</span><div><h2 id="archive-title">The aviation maintenance archive</h2><p>Historical issue dates organize the editorial archive. Each article separately states when Northbound Labs actually published it.</p></div></header><div className="publication-list">{articles.map((item, index) => <a className="publication" href={`/articles/${item.slug}`} key={item.slug}><div className="publication-number">{String(index + 1).padStart(2, '0')}</div><div className="publication-date">{formatIssue(item.issueDate)}</div><div className="publication-copy"><div className="publication-meta"><span>{item.articleType}</span><span>{item.estimatedReadingTime} min</span></div><h3>{item.title}</h3><p>{item.summary}</p></div><span className="publication-arrow">↗</span></a>)}</div></section>
    </div><aside className="year-rail" aria-label="Archive by year"><div className="rail-sticky"><div className="rail-label">Archive index</div><div className="rail-current"><span>Published issues</span><strong>{articles.length}</strong></div><div className="year-list">{archiveYears.map(({ year, articles: yearArticles }) => <details key={year} open={year === 2026}><summary><span>{year}</span><span>{yearArticles.length ? `${yearArticles.length} ${yearArticles.length === 1 ? 'issue' : 'issues'}` : 'Planned collection'}</span></summary><div className="month-grid">{months.map((month, index) => { const article = yearArticles.find((item) => Number(item.issueDate.slice(5,7)) === index + 1); return article ? <a className="month-link active-month" href={`/articles/${article.slug}`} key={month}>{month}</a> : <span className="month-pending" aria-disabled="true" title={`${month} ${year} is not yet published`} key={month}>{month}</span>; })}</div></details>)}</div></div></aside></div>
    <footer id="about" className="site-footer"><div><span className="brand-mark small">N</span> Northbound Labs</div><p>Independent research on aviation maintenance, MRO modernization, applied AI, aircraft systems, and the technology connecting operational evidence to human decisions.</p><div><a href="/feed.xml">RSS</a> · <a href="/sitemap.xml">Sitemap</a></div></footer>
  </main>;
}
