import type { Metadata } from 'next';
import { ArticleShell } from '../../components/ArticleShell';
import { ExecutiveSummary, KeyTakeaways, ReferenceList } from '../../components/Publication';
import type { ArticleRecord } from '../../lib/articles';
const article:ArticleRecord={id:'nbl-2026-09-25',title:'Replay Is a Reliability Feature, Not Just a Data Engineering Feature',slug:'2026-09-replayable-maintenance-intelligence',issueDate:'2026-09-25',publishedAt:'2026-09-25T19:00:00-05:00',updatedAt:'2026-09-25T19:00:00-05:00',summary:'A governed architecture for replaying aircraft and maintenance evidence when logic, schemas, or late data change, without erasing what engineers knew at decision time.',description:'A reproducible reliability architecture using immutable evidence, versioned processing, idempotent consumers, replay controls, and decision-time history.',categories:['Reliability Engineering','Data & Cloud Architecture'],topicTags:['Replay','Event sourcing','Evidence lineage'],ataChapters:[],articleType:'Reference Architecture',estimatedReadingTime:9,publicationStatus:'published',featuredStatus:'featured',diagramIdentifiers:['replayable-maintenance-intelligence'],referenceCount:5,relatedArticleSlugs:['2026-09-reliability-alert-latency','2026-08-maintenance-event-ledger'],previousArticleSlug:'2026-09-reliability-alert-latency',nextArticleSlug:null};
export const metadata:Metadata={title:article.title,description:article.description,alternates:{canonical:'/articles/'+article.slug}};
const flow='AIRCRAFT + MAINTENANCE EVIDENCE\n telemetry · faults · work events · removals · configuration\n                 |\n                 v\n       Identity + time + schema gate\n                 |\n       +---------+---------+\n       |                   |\n       v                   v\n Immutable raw evidence   quarantine / repair\n       |                   |\n       v                   |\n    Domain event stream <--+\n       |\n  +----+----------------+\n  |                     |\n  v                     v\nLIVE PROCESSING    CONTROLLED REPLAY\nrules/models vN    range + reason + version\n  |                     |\n  +----> idempotent <----+\n        projections\n             |\n             v\n reliability cases + evidence packages\n             |\n             v\n qualified human review\n             |\n             +--> decision-time view + reconstructed view';
export default function Page(){return <ArticleShell article={article}>
<ExecutiveSummary><p>Replay is often treated as a data-engineering recovery tool. In aircraft reliability systems it has a larger job: recompute analytical state when late evidence arrives, a defect rule changes, a schema is corrected, or a model is replaced, while preserving what engineers actually knew when an earlier decision was made.</p><p>The pattern is to preserve source evidence immutably, version each interpretation, make consumers safe to execute repeatedly, and never let reconstruction silently overwrite decision-time history.</p></ExecutiveSummary>
<section><h2>1. Reliability knowledge changes</h2><p>Aircraft evidence does not always arrive as one ordered transaction. Telemetry may be buffered or offloaded later, maintenance records may close after an operational event, and configuration context can arrive after an initial result. AWS's connected-aircraft reference architecture explicitly includes both near-real-time events and flight-data offload at the gate. Delayed evidence is therefore a design condition, not merely an exception.</p></section>
<section><h2>2. Separate evidence from interpretation</h2><p>Preserve source payloads or governed canonical records with aircraft/component identity, source event time, ingestion time, provenance, schema version, and integrity metadata. Put chronic-defect classifications, anomaly scores, alert states, and trends in versioned projections. When logic changes, the new interpretation can be computed without pretending it existed earlier.</p></section>
<section><h2>3. Reference architecture</h2><p>This original Northbound Labs flow separates live processing from controlled replay and joins both at idempotent projections.</p><pre aria-label="Replayable maintenance intelligence architecture"><code>{flow}</code></pre><p>AWS Prescriptive Guidance describes event sourcing as retaining state-changing events in an immutable, append-only history so state can be reconstructed. EventBridge archives can replay events over a selected time range. Those are useful building blocks; the operator still owns the controls around who can replay what, with which version, and how outputs are labeled.</p></section>
<section><h2>4. Replay must be explainable</h2><p>Record versions of transformation code, schemas, reference data, rules, and models. A replay manifest should state the evidence interval, reason, processing versions, initiating identity, destination, and resulting projection version.</p><p>Do not assume infrastructure replay preserves business sequence. Amazon EventBridge documentation states that archived events are not necessarily replayed in exactly the order they entered the archive. Where reliability logic requires ordering, establish it at the domain layer with event time, sequence information, or an ordered stream/queue appropriate to the requirement.</p></section>
<section><h2>5. Idempotency protects analytical quality</h2><p>Replay deliberately causes repeated processing. Consumers must not create duplicate cases, alerts, or work requests. Use stable event identities and idempotency keys. Keep external side effects behind explicit replay policies: recomputing a score may be safe, while reissuing a notification or opening another case may not be.</p></section>
<section><h2>6. Preserve two histories</h2><p>Retain a <strong>decision-time view</strong> showing what the system presented when an operational decision occurred and a <strong>reconstructed view</strong> showing what the same interval produces after late data or improved logic. This answers two legitimate questions: “What did we know then?” and “What does the evidence tell us now?”</p></section>
<section><h2>7. Govern replay as a production operation</h2><p>Require a reason code, bounded evidence window, approved processing version, shadow destination for material changes, reconciliation checks, and explicit promotion before reconstructed projections become current. Monitor replay volume, duplicate suppression, quarantined events, projection deltas, blocked side effects, and failures. Large unexplained deltas deserve investigation, not applause.</p></section>
<section><h2>8. Keep maintenance authority separate</h2><p>FAA AC 120-17B remains active and describes controlled reliability-program methods and continuing evaluation. Replayable analytics can improve traceability and evaluation, but they do not create maintenance authority. Keep reconstructed analytics distinct from approved maintenance data, required records, and qualified disposition. AI may compare versions or summarize changed evidence, but it should expose provenance and uncertainty.</p></section>
<section><h2>9. Pilot it narrowly</h2><p>Choose one reliability use case with known late-arriving evidence. Retain a bounded source interval, build one idempotent projection, capture a replay manifest, then introduce a controlled rule change. Compare original and reconstructed views and measure reproducibility, duplicate suppression, changed classifications, and whether an engineer can explain each material delta.</p></section>
<KeyTakeaways><ul><li>Replay is a reliability-product feature, not only disaster recovery.</li><li>Preserve immutable evidence and version interpretations separately.</li><li>Make consumers idempotent and govern side effects explicitly.</li><li>Retain decision-time and reconstructed analytical views.</li><li>Do not assume replay provides strict domain ordering.</li><li>Keep analytics distinct from approved maintenance authority.</li></ul></KeyTakeaways>
<section><h2>Editorial note</h2><p>This independent engineering reference architecture is not FAA-approved maintenance data, an operator reliability-program procedure, or instructions for continued airworthiness. AWS services are illustrative. Production use should be evaluated against approved programs, records requirements, cybersecurity controls, data governance, and applicable obligations.</p></section>
<ReferenceList><li><a href="https://www.faa.gov/regulations_policies/advisory_circulars/index.cfm/go/document.information/documentid/1035253">FAA AC 120-17B — Reliability Program Methods</a></li><li><a href="https://docs.aws.amazon.com/reference-architecture-diagrams/latest/connected-aircraft-solution-architecture/connected-aircraft-solution-architecture.html">AWS — Connected Aircraft Solution Architecture</a></li><li><a href="https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/event-sourcing-pattern.html">AWS Prescriptive Guidance — Event sourcing pattern</a></li><li><a href="https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-replay-archived-event.html">Amazon EventBridge — Replaying archived events</a></li><li><a href="https://docs.aws.amazon.com/prescriptive-guidance/latest/modernization-integrating-microservices/eventbridge.html">AWS Prescriptive Guidance — Amazon EventBridge</a></li></ReferenceList>
</ArticleShell>}