import type { Metadata } from 'next';
import { ArticleShell } from '../../components/ArticleShell';
import { ExecutiveSummary, KeyTakeaways, ReferenceList } from '../../components/Publication';
import type { ArticleRecord } from '../../lib/articles';

const article: ArticleRecord={id:'nbl-2026-09-11',title:'Maintenance Event Contracts: The Missing Layer Between MRO Systems and AI',slug:'2026-09-maintenance-event-contracts',issueDate:'2026-09-11',publishedAt:'2026-09-11T19:00:00-05:00',updatedAt:'2026-09-11T19:00:00-05:00',summary:'A practical architecture for versioning the meaning, identity, timing, provenance, and authority of aircraft maintenance events before analytics and AI consume them.',description:'How airlines can use governed event contracts to connect authoritative MRO systems, aircraft telemetry, reliability products, and AI without turning integration semantics into hidden technical debt.',categories:['MRO Modernization','Cloud Architecture'],topicTags:['Event contracts','Aircraft maintenance','AWS architecture'],ataChapters:[],articleType:'Engineering Guide',estimatedReadingTime:10,publicationStatus:'published',featuredStatus:'featured',diagramIdentifiers:['maintenance-event-contract-flow'],referenceCount:5,relatedArticleSlugs:[],previousArticleSlug:null,nextArticleSlug:null};

export const metadata:Metadata={title:article.title,description:article.description,alternates:{canonical:`/articles/${article.slug}`}};

const flow=`MRO / parts / telemetry / operations\n              |\n              v\n+--------------------------------+\n| MAINTENANCE EVENT CONTRACT     |\n| event + schema version         |\n| aircraft/component identity    |\n| event time + ingestion time    |\n| source + provenance            |\n| effectivity + quality state    |\n| idempotency / correlation IDs  |\n+-----------+--------------------+\n            | valid                 invalid -> quarantine / repair\n            v\n     Event bus + archive\n            |\n       replay / route\n            v\n  Versioned consumer projections\n      /          |           \\\nReliability   Ops views    AI evidence assembly\n      \\          |           /\n            v\n Qualified human review / disposition`;

export default function Page(){return <ArticleShell article={article}>
<ExecutiveSummary><p>Airlines increasingly connect maintenance transactions, aircraft telemetry, operational events, reliability analytics, and AI through event-driven architectures. The hard part is not moving JSON. It is preserving what each event means as producers, fleets, software versions, and consumers change.</p><p>This article proposes a maintenance event contract: a governed interface defining identity, timing, provenance, effectivity, quality, versioning, and authority. It sits between authoritative systems and downstream products; it does not replace the MRO system of record, approved maintenance data, or qualified judgment.</p></ExecutiveSummary>
<section><h2>1. An event is more than a payload</h2><p>A message such as <code>workOrder.completed</code> looks simple until a reliability service asks what completed means: task signed, administratively closed, released, or merely moved to a terminal application state. Which aircraft configuration was effective? Was a component changed? Can the consumer distinguish source event time from ingestion time?</p><p>If every consumer independently reverse-engineers those semantics, the enterprise creates multiple unofficial interpretations of the same maintenance state. AI magnifies the weakness because fluent synthesis can conceal inconsistent upstream meaning.</p></section>
<section><h2>2. Contract the maintenance meaning</h2><p>A useful contract carries a stable event ID, business-event type, schema version, authoritative source, aircraft and relevant component identity, event time, ingestion time, correlation or causation identifiers, and an idempotency key. Where applicable it should carry configuration/effectivity and quality state, while linking back to authoritative records rather than copying uncontrolled technical content.</p><p>Recorded facts must remain separate from derived classifications. A source discrepancy code is evidence; a normalized symptom family is interpretation. Preserving both lets engineering reproduce historical results after mappings evolve.</p></section>
<section><h2>3. Reference architecture</h2><p>This original Northbound Labs flow keeps authoritative transactions at their source and makes semantic validation an explicit integration boundary.</p><pre aria-label="Maintenance event contract architecture"><code>{flow}</code></pre><p>On AWS, EventBridge can route events and its schema registry can make contracts discoverable. Durable evidence can be retained for replay, while SQS can isolate consumers requiring independent retry and back-pressure. Service choice is secondary to preserving contract, failure-path, and replay semantics.</p></section>
<section><h2>4. Version meaning, not only syntax</h2><p>Schema compatibility is necessary but insufficient. An optional field can be structurally backward-compatible while changing business interpretation. Maintenance event governance therefore needs both structural compatibility and semantic release notes. Breaking semantic changes should create a new contract version with an explicit migration window.</p><p>Do not let integration code “fix” an unknown enum, missing aircraft identity, or impossible timestamp by guessing. Quarantine it with the original payload and validation reason intact.</p></section>
<section><h2>5. Design for duplicates, lateness, and replay</h2><p>Distributed systems retry, and aircraft evidence can arrive later than ground-system transactions because connectivity and offload patterns vary. Consumers should be idempotent, distinguish event time from ingestion time, and tolerate late evidence according to the supported decision.</p><p>Replay should be tested, not theoretical. A corrected mapping or reliability rule should rebuild a derived projection from retained source evidence without rewriting historical source events.</p></section>
<section><h2>6. Put AI behind the evidence boundary</h2><p>AI services should consume governed projections or evidence packages, not unrestricted streams with evolving semantics. Packages should identify source records, versions, timestamps, applicability, and unresolved quality conditions. Generated synthesis must remain distinguishable from recorded maintenance facts.</p><p>AI can organize evidence, retrieve related cases, or prioritize review. It should not turn an analytical inference into approved maintenance instruction or maintenance authority.</p></section>
<section><h2>7. Roll out one event family at a time</h2><p>Start with one valuable family such as discrepancy opened, corrective action recorded, component removed, or work order completed. Reconstruct real lifecycle examples with maintenance, reliability, data, and integration engineers. Include corrections and exceptions, then shadow consumers before replacing existing interfaces.</p><p>Measure contract rejection, unresolved identity, late-event and duplicate rates, consumer lag, replay success, and repair time. Those measures reveal modernization health better than counting messages on a bus.</p></section>
<KeyTakeaways><ul><li>Define maintenance events as governed business contracts, not convenient JSON.</li><li>Preserve identity, event time, ingestion time, provenance, effectivity, and version.</li><li>Quarantine ambiguity instead of inventing missing meaning.</li><li>Make consumers idempotent and replay a tested capability.</li><li>Keep AI downstream of governed evidence and preserve qualified human authority.</li></ul></KeyTakeaways>
<section><h2>Editorial note</h2><p>This independent engineering reference architecture is not FAA-approved maintenance data, an operator maintenance-program procedure, or instructions for continued airworthiness. AWS services are illustrative components, not a claim that a particular airline must use them. Adoption should be evaluated against approved programs, security requirements, data governance, and applicable obligations.</p></section>
<ReferenceList><li><a href="https://www.faa.gov/regulations_policies/advisory_circulars/index.cfm/go/document.information/documentid/1035253">FAA AC 120-17B — Reliability Program Methods</a></li><li><a href="https://docs.aws.amazon.com/wellarchitected/latest/serverless-applications-lens/event-driven-architectures.html">AWS Well-Architected — Event-driven architectures</a></li><li><a href="https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-schema-registry.html">Amazon EventBridge — Schema registries</a></li><li><a href="https://docs.aws.amazon.com/reference-architecture-diagrams/latest/connected-aircraft-solution-architecture/connected-aircraft-solution-architecture.html">AWS Connected Aircraft Solution Architecture</a></li><li><a href="https://docs.aws.amazon.com/reference-architecture-diagrams/latest/aircraft-predictive-maintenance/aircraft-predictive-maintenance.html">AWS Aircraft Predictive Maintenance</a></li></ReferenceList>
</ArticleShell>}
