import Image from 'next/image';

type AwsServiceProps={icon:string;name:string;role:string;compact?:boolean};

function AwsService({icon,name,role,compact=false}:AwsServiceProps){return <div className="aws-service" data-compact={compact||undefined}><Image src={`/aws-icons/${icon}.svg`} alt="" width={48} height={48}/><div><b>{name}</b><small>{role}</small></div></div>}
function Flow({label,tone='sync',direction='right'}:{label:string;tone?:'sync'|'event'|'failure';direction?:'left'|'right'}){return <div className="aws-flow" data-tone={tone} data-direction={direction}><span>{label}</span><i aria-hidden="true">{direction==='left'?'←':'→'}</i></div>}

export function AwsServerlessMroArchitecture(){return <article className="lab-entry aws-lab-entry"><header className="lab-entry-header"><span>A01</span><div><p>AWS reference architecture · serverless MRO</p><h2>Maintenance discrepancy to controlled work order</h2><dl><div><dt>Operational problem</dt><dd>Turn a line-maintenance discrepancy into a traceable case without coupling the technician interface to the MRO system of record.</dd></div><div><dt>Architecture decision</dt><dd>Use a synchronous intake boundary, asynchronous domain events, durable orchestration, and an explicit human authorization gate.</dd></div><div><dt>Failure strategy</dt><dd>Idempotent commands, persisted workflow state, bounded retries, a dead-letter queue, replay, and end-to-end correlation IDs.</dd></div></dl></div></header><figure id="figure-a01" className="lab-figure aws-figure" aria-labelledby="title-a01" aria-describedby="caption-a01"><div className="aws-title"><div><span>AWS CLOUD · REFERENCE PATTERN</span><h3 id="title-a01">Serverless maintenance discrepancy orchestration</h3></div><div className="aws-title-key"><span><i data-tone="sync"/>Request / response</span><span><i data-tone="event"/>Domain event</span><span><i data-tone="failure"/>Failure / replay</span></div></div><div className="aws-canvas" role="img" aria-label="AWS architecture showing a technician and maintenance control application sending a discrepancy through API Gateway and Lambda, EventBridge and Step Functions coordinating evidence and human review, DynamoDB and S3 retaining state and evidence, an SQS queue isolating the MRO system adapter, and observability and security services spanning the workload.">
  <section className="aws-zone aws-edge-zone"><header>Airline / MRO environment</header><div className="aws-actor"><span>TECH</span><b>Technician</b><small>record discrepancy</small></div><div className="aws-external"><b>Maintenance control</b><small>review evidence · authorize action</small></div><div className="aws-external"><b>MRO system of record</b><small>create / update work order</small></div></section>
  <div className="aws-ingress-flow"><Flow label="POST /discrepancies"/></div>
  <section className="aws-zone aws-region"><header><span>AWS Region</span><small>production account · private data plane where supported</small></header>
    <div className="aws-column aws-intake"><em>1 · INTAKE</em><AwsService icon="api-gateway" name="Amazon API Gateway" role="authenticated REST boundary"/><Flow label="validate + authorize"/><AwsService icon="lambda" name="AWS Lambda" role="command adapter · idempotency"/></div>
    <div className="aws-column aws-coordinate"><em>2 · COORDINATE</em><AwsService icon="eventbridge" name="Amazon EventBridge" role="maintenance domain event bus"/><Flow label="DiscrepancyRecorded" tone="event"/><AwsService icon="step-functions" name="AWS Step Functions" role="case workflow · wait for review"/></div>
    <div className="aws-column aws-services"><em>3 · RESOLVE + RETAIN</em><div className="aws-service-pair"><AwsService icon="lambda" name="Evidence resolver" role="effectivity · history · limits" compact/><AwsService icon="dynamodb" name="Amazon DynamoDB" role="case state · idempotency" compact/><AwsService icon="s3" name="Amazon S3" role="immutable evidence package" compact/></div></div>
    <div className="aws-human-gate"><span>HUMAN AUTHORITY BOUNDARY</span><b>Maintenance control accepts, defers, or returns for evidence</b><small>The workflow may recommend a path; it cannot confer maintenance authority.</small></div>
    <div className="aws-column aws-integrate"><em>4 · INTEGRATE</em><AwsService icon="sqs" name="Amazon SQS" role="work-order command buffer"/><Flow label="bounded retry" tone="event"/><AwsService icon="lambda" name="AWS Lambda" role="MRO anti-corruption adapter"/><div className="aws-dlq"><Flow label="poison message" tone="failure"/><AwsService icon="sqs" name="Dead-letter queue" role="alarm · inspect · redrive" compact/></div></div>
    <aside className="aws-crosscut"><b>Workload controls</b><AwsService icon="cloudwatch" name="Amazon CloudWatch" role="logs · metrics · alarms" compact/><AwsService icon="x-ray" name="AWS X-Ray" role="distributed traces" compact/><AwsService icon="cloudtrail" name="AWS CloudTrail" role="control-plane audit" compact/><AwsService icon="kms" name="AWS KMS" role="encryption keys" compact/></aside>
  </section>
  <div className="aws-control-return"><Flow label="review task" tone="event" direction="left"/></div><div className="aws-mro-flow"><Flow label="authorized command" tone="event" direction="left"/></div>
  <ol className="aws-callouts"><li><b>Fast acknowledgement.</b> Intake returns a case identifier; downstream enrichment does not hold the technician request open.</li><li><b>Authority stays human.</b> Step Functions pauses at the operational decision instead of silently creating approved maintenance work.</li><li><b>System isolation.</b> SQS absorbs MRO outages and rate limits; failed messages move to a DLQ rather than disappearing.</li><li><b>Traceable evidence.</b> One correlation ID links the API request, event, state transition, evidence object, approval, and work order.</li></ol>
 </div><figcaption id="caption-a01"><span>Reference pattern for a common MRO integration problem: controlled discrepancy intake, evidence assembly, authorization, and work-order synchronization.</span><strong>Conceptual architecture · service selection and sizing require workload validation</strong></figcaption></figure></article>}
