import type { Metadata } from 'next';
import { ArticleShell } from '../../components/ArticleShell';
import type { ArticleRecord } from '../../lib/articles';
import { PublicationVisual, type PublicationVisualContext } from '../../../src/components/publication';

const article: ArticleRecord = {
  id:'nbl-2026-09-04', title:'Aircraft Telemetry Has Two Clocks. Reliability Engineering Needs Both.', slug:'2026-09-telemetry-time-integrity', issueDate:'2026-09-04',
  publishedAt:'2026-09-04T19:00:00-05:00', updatedAt:'2026-09-04T19:00:00-05:00',
  summary:'A reference architecture for preserving event time, ingestion time, late-arriving aircraft data, and maintenance context so reliability signals remain reproducible.',
  description:'How to design aircraft telemetry pipelines that distinguish when an event happened from when the enterprise received it.',
  categories:['Aircraft Data','Reliability Engineering'], topicTags:['Aircraft telemetry','Event time','Late-arriving data'], ataChapters:[],
  articleType:'Engineering Guide', estimatedReadingTime:10, publicationStatus:'published', featuredStatus:'featured',
  diagramIdentifiers:['telemetry-time-integrity'], referenceCount:4, relatedArticleSlugs:['2026-02-event-driven-aircraft-telemetry','2026-08-exposure-normalized-reliability','2026-08-maintenance-event-ledger'],
  previousArticleSlug:'2026-08-maintenance-event-ledger', nextArticleSlug:null
};

export const metadata: Metadata = {title:article.title,description:article.description,alternates:{canonical:`/articles/${article.slug}`},openGraph:{type:'article',title:article.title,description:article.description,publishedTime:article.publishedAt}};

export default function TelemetryTimeIntegrityPage(){
 const visualContext: PublicationVisualContext={slug:article.slug,title:article.title,domain:'aircraft telemetry and reliability engineering',tags:article.topicTags,ata:[],issueDate:article.issueDate,brief:'A time-aware telemetry architecture that preserves event time, receipt time, corrections, and maintenance context for reproducible reliability analysis.'};
 const mermaid=`flowchart LR
  A[Aircraft / onboard source] -->|event time + source identity| B[Ground ingestion]
  B -->|add ingestion time| C{Identity + time valid?}
  C -- No --> Q[Quarantine / quality review]
  C -- Yes --> R[(Immutable raw evidence)]
  C -- Yes --> S[Stream processing]
  S --> W[Event-time windows + watermark policy]
  W --> T[(Time-series / derived signals)]
  R -->|late data / correction replay| W
  M[Maintenance + configuration events] --> J[Temporal correlation layer]
  T --> J
  J --> E[Reliability evidence product]
  E --> H[Qualified engineering review]`;
 return <ArticleShell article={article}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.updatedAt,mainEntityOfPage:`https://northboundlabs.ai/articles/${article.slug}`,author:{'@type':'Person',name:'Chaitanya Koredla'},publisher:{'@type':'Organization',name:'Northbound Labs'}})}} />
  <div className="article-body">
   <p className="lead">Aircraft data does not arrive in the enterprise in the same order that the aircraft experienced it. Gate offload, intermittent connectivity, buffering, vendor relays, retries, and downstream corrections can separate <em>event time</em> from <em>ingestion time</em>. Reliability engineering needs both clocks. If a platform keeps only the time a record reached the cloud, it can quietly rewrite the operational sequence it is supposed to explain.</p>
   <section><h2>Executive summary</h2><p>A telemetry record should answer two different questions: when did the observation occur at the source, and when did the enterprise receive or process it? Treat those timestamps as separate evidence. Preserve the raw observation, record source identity and clock quality, define an explicit late-data policy, and make derived reliability signals reproducible when delayed or corrected data arrives.</p><p>This is not a claim that every aircraft produces real-time streaming telemetry. AWS's connected-aircraft reference architecture explicitly includes both near-real-time events and flight data offloaded to Amazon S3 at the gate. That mixed arrival pattern is exactly why time semantics belong in the data contract rather than in analyst folklore.</p></section>
   <section><h2>1. The sequence can be wrong even when every record is right</h2><p>Imagine a fault observation recorded onboard at 14:03, a maintenance action recorded on the ground at 14:25, and the flight-data batch reaching the cloud at 14:41. If an analytical pipeline orders everything by cloud receipt time, the fault appears to occur after the maintenance action. Nothing was fabricated; the platform simply chose the wrong clock.</p><p>That error becomes more consequential when teams compute pre/post-maintenance windows, repeat-defect rates, anomaly sequences, or model features. A time-aware system therefore keeps at least event time, ingestion time, source-system identity, and a stable event identifier. Where source clock confidence is uncertain, preserve that uncertainty instead of manufacturing precision.</p></section>
   <section><h2>2. Reference architecture</h2><p>The architecture below keeps raw evidence immutable, separates validation from interpretation, and lets late observations or corrections recompute derived windows without rewriting the original history.</p><PublicationVisual context={visualContext} role="hero"/><details><summary>Mermaid source for the reference architecture</summary><pre><code>{mermaid}</code></pre></details><p><strong>Design reading:</strong> the source contributes event time; ground ingestion adds receipt time. Invalid identity or implausible time relationships are quarantined. Valid evidence is retained before stream processing. Event-time windows create derived signals, while retained evidence supports controlled replay when late data arrives. Maintenance and configuration events join through a temporal correlation layer before anything is presented as reliability evidence.</p></section>
   <section><h2>3. Make time semantics part of the contract</h2><p>A practical telemetry envelope should distinguish <code>event_time</code>, <code>ingested_at</code>, source clock or sequence information when available, aircraft identity, flight or leg context when applicable, parameter identity and units, schema version, source reference, and an immutable event ID. A derived record should additionally carry the processing version and the evidence interval used to compute it.</p><p>Do not silently replace event time with ingestion time when event time is missing. Mark the observation accordingly and decide whether the downstream use case can tolerate it. A fleet dashboard may accept degraded timing; a causal pre/post-maintenance analysis may not.</p></section>
   <section><h2>4. Late data is normal architecture, not an exception handler</h2><p>AWS Timestream documentation explicitly addresses data whose ingestion is significantly delayed relative to its timestamp. It describes catch-up scheduled computations for predictable delays and manual executions for unpredictable late arrivals or corrections. The broader lesson applies beyond Timestream: derived products need a declared correction window and a controlled recomputation path.</p><p>For stream processing, define event-time windows and a lateness policy rather than assuming arrival order is operational order. For batch offload, retain raw files and their provenance so a corrected parser, mapping, or time rule can rebuild the derived signal. The raw layer is evidence; the aggregate is a versioned interpretation.</p></section>
   <PublicationVisual context={visualContext} role="evidence"/>
   <section><h2>5. Reliability joins need temporal effectivity</h2><p>Telemetry becomes maintenance evidence only after it is joined to the right aircraft state. Component serial number, installed position, software/configuration standard, maintenance completion time, and operating exposure can change the meaning of the same parameter value. A conventional current-state join can attach today's configuration to yesterday's observation.</p><p>Use effective-from/effective-to intervals or equivalent versioned configuration history. Correlate maintenance actions to observations using event time, then preserve the join version so the result can be reproduced. FAA AC 120-17B describes reliability programs in terms of monitored performance and standards; software should support that accountable analysis without pretending a telemetry correlation is itself maintenance authority.</p></section>
   <section><h2>6. AWS implementation pattern</h2><p>A connected-aircraft implementation can land immutable raw flight evidence in Amazon S3, process streams with Amazon Managed Service for Apache Flink where appropriate, and create queryable time-series or analytical projections. AWS's connected-aircraft architecture illustrates S3-based flight-data offload alongside near-real-time processing. Timestream documentation provides explicit patterns for late-arriving data and scheduled recomputation.</p><p>The service choice is secondary to five controls: preserve both clocks; keep raw evidence; version transformations; quarantine unresolved identity/time anomalies; and make recomputation observable. Measure event-time lag, ingestion lag, late-event rate, quarantined records, replay volume, and the number of derived signals changed by late evidence. Those metrics tell you whether the reliability picture is stable or merely current.</p></section>
   <section><h2>7. A useful pilot</h2><p>Choose one aircraft health message or parameter family and one maintenance outcome. Preserve source event time and cloud ingestion time, join against versioned aircraft/configuration context, and build a pre/post-maintenance evidence window. Then deliberately inject delayed observations and verify that the derived result changes predictably, is versioned, and remains traceable to raw evidence.</p><p>If the team cannot explain why a point belongs before or after a maintenance action after replay, the pipeline is not ready for more sophisticated AI. A model can be statistically impressive and still learn from a timeline the aircraft never lived.</p></section>
   <section><h2>Editorial note</h2><p>This article is independent engineering analysis and a reference architecture. It does not describe or claim implementation by any specific airline, manufacturer, MRO, or employer. It is not approved maintenance data, regulatory interpretation, or an operator procedure. Maintenance and return-to-service authority remain with applicable approved programs and qualified personnel. AWS services are illustrative choices, not endorsements or requirements.</p></section>
   <section id="references"><h2>Sources</h2><ul>
    <li><a href="https://www.faa.gov/regulations_policies/advisory_circulars/index.cfm/go/document.information/documentid/1035253">FAA AC 120-17B, Reliability Program Methods—Standards for Determining Time Limitations (active; editorial update July 9, 2026)</a></li>
    <li><a href="https://docs.aws.amazon.com/architecture-diagrams/latest/connected-aircraft-solution-architecture/connected-aircraft-solution-architecture.html">AWS Connected Aircraft Solution Architecture</a></li>
    <li><a href="https://docs.aws.amazon.com/timestream/latest/developerguide/scheduledqueries-patterns-latearrive.html">Amazon Timestream for LiveAnalytics, Handling late-arriving data</a></li>
    <li><a href="https://docs.aws.amazon.com/timestream/latest/developerguide/configuration.html">Amazon Timestream for LiveAnalytics, Configuration and retention guidance</a></li>
   </ul></section>
  </div>
 </ArticleShell>;
}