import type { PublicationMode, PublicationVisualContext, VisualRole, VisualVariant } from './types';

export type VisualFamily='aws-architecture'|'architecture'|'topology'|'dashboard'|'timeline'|'decision-tree'|'heatmap'|'service-blueprint'|'journey-map'|'knowledge-graph'|'aircraft'|'metrics'|'infographic'|'risk'|'table';
export type VisualProfile='cloud'|'aircraft-system'|'reliability'|'workflow'|'materials'|'records'|'ai-assurance'|'governance'|'general';
type RolePlan={family:VisualFamily;variant:VisualVariant;question:string};

const modes:PublicationMode[]=['research','briefing','handbook','field-guide','technical-manual','playbook','decision-record','case-study'];
const profilePlans:Record<VisualProfile,Record<VisualRole,RolePlan>>={
  cloud:{hero:{family:'aws-architecture',variant:'a',question:'Which AWS and MRO boundaries carry the workload from operational intake to a controlled system-of-record update?'},evidence:{family:'topology',variant:'a',question:'Where does evidence change custody, connectivity, or persistence?'},analysis:{family:'dashboard',variant:'a',question:'Which signals reveal workload health, delay, and failure recovery?'},decision:{family:'risk',variant:'a',question:'Which failure modes require control, escalation, or a stop boundary?'}},
  'aircraft-system':{hero:{family:'aircraft',variant:'a',question:'Where is the affected system installed and which configuration boundary governs applicability?'},evidence:{family:'topology',variant:'b',question:'How do energy, signal, and fault effects propagate through the aircraft system?'},analysis:{family:'metrics',variant:'a',question:'How does observed behavior compare across operating regimes and exposure?'},decision:{family:'timeline',variant:'a',question:'Which evidence and review gates must be satisfied before action?'}},
  reliability:{hero:{family:'metrics',variant:'a',question:'What distribution, exposure, or trend establishes the reliability concern?'},evidence:{family:'timeline',variant:'b',question:'How do events, maintenance actions, and confirmed outcomes relate over time?'},analysis:{family:'heatmap',variant:'a',question:'Where is the concern concentrated by fleet, configuration, position, or cohort?'},decision:{family:'risk',variant:'a',question:'Which reliability signals warrant monitoring, investigation, or intervention?'}},
  workflow:{hero:{family:'service-blueprint',variant:'a',question:'How do people, interfaces, services, and records coordinate the maintenance decision?'},evidence:{family:'journey-map',variant:'a',question:'Where does the operator encounter delay, ambiguity, or authority handoff?'},analysis:{family:'timeline',variant:'a',question:'Which states and gates control progression and recovery?'},decision:{family:'decision-tree',variant:'a',question:'Which explicit conditions lead to action, rework, abstention, or escalation?'}},
  materials:{hero:{family:'topology',variant:'a',question:'How do part identity, condition, custody, and demand connect across the network?'},evidence:{family:'timeline',variant:'a',question:'Which lifecycle events establish the component or material state?'},analysis:{family:'heatmap',variant:'a',question:'Where are shortages, removals, or repair constraints concentrated?'},decision:{family:'table',variant:'a',question:'Which planning choice follows from each evidence and uncertainty condition?'}},
  records:{hero:{family:'knowledge-graph',variant:'a',question:'Which governed identities and relationships connect the technical evidence?'},evidence:{family:'service-blueprint',variant:'c',question:'How is evidence created, reviewed, corrected, and accepted into the record?'},analysis:{family:'table',variant:'a',question:'Which information classes require provenance, version, and authority controls?'},decision:{family:'timeline',variant:'a',question:'Which record states and review gates establish completeness?'}},
  'ai-assurance':{hero:{family:'architecture',variant:'a',question:'Where do evidence, model inference, safeguards, and human authority sit in the decision system?'},evidence:{family:'knowledge-graph',variant:'a',question:'Which sources support each model claim and where can applicability break?'},analysis:{family:'risk',variant:'a',question:'Which AI failure modes change operational consequence or required control?'},decision:{family:'decision-tree',variant:'a',question:'When should the system answer, abstain, or escalate to qualified review?'}},
  governance:{hero:{family:'risk',variant:'a',question:'Which hazards and uncertainties determine control intensity?'},evidence:{family:'table',variant:'a',question:'Which claim, evidence, owner, and control must be traceable?'},analysis:{family:'heatmap',variant:'a',question:'Where are assurance gaps concentrated across the operating envelope?'},decision:{family:'decision-tree',variant:'a',question:'Which evidence permits release, restriction, rollback, or withdrawal?'}},
  general:{hero:{family:'infographic',variant:'a',question:'What is the essential engineering model the reader must retain?'},evidence:{family:'table',variant:'a',question:'Which evidence classes and controls must be compared directly?'},analysis:{family:'metrics',variant:'a',question:'What measurable behavior distinguishes the important conditions?'},decision:{family:'decision-tree',variant:'a',question:'Which conditions determine the next accountable action?'}}
};

function contextText(context:PublicationVisualContext){return `${context.title} ${context.domain} ${context.tags.join(' ')}`.toLowerCase()}
export function visualProfile(context:PublicationVisualContext):VisualProfile{const text=contextText(context);if(/cloud|serverless|aws|event-driven|event stream|telemetry|edge analytics|integration|observability|migration/.test(text))return'cloud';if(context.ata.length||/apu|landing gear|flight control|electrical|pneumatic|aircraft system/.test(text))return'aircraft-system';if(/ai|machine learning|copilot|agent|computer vision|generative|nlp|model/.test(text))return /governance|assurance|safety case/.test(text)?'governance':'ai-assurance';if(/part|material|inventory|supply|rotable|aog|repair cycle/.test(text))return'materials';if(/record|document|lineage|knowledge graph|configuration|traceability/.test(text))return'records';if(/workflow|task card|work package|maintenance control|dispatch|inspection|execution|handover/.test(text))return'workflow';if(/reliability|defect|failure|predictive|condition|health|trend|recurrence/.test(text))return'reliability';if(/security|risk|governance|assurance|authority/.test(text))return'governance';return'general'}
export function visualSelection(context:PublicationVisualContext,role:VisualRole){const profile=visualProfile(context);return{...profilePlans[profile][role],profile}}
export function publicationMode(context:Pick<PublicationVisualContext,'slug'|'issueDate'>):PublicationMode{const year=Number(context.issueDate.slice(0,4));const month=Number(context.issueDate.slice(5,7));return modes[(year+month)%modes.length]}
export const visualFamilies=[...new Set(Object.values(profilePlans).flatMap(plan=>Object.values(plan).map(item=>item.family)))];
