import type { PublicationMode, PublicationVisualContext, VisualRole, VisualVariant } from './types';
export type VisualFamily='architecture'|'topology'|'dashboard'|'timeline'|'decision-tree'|'heatmap'|'service-blueprint'|'journey-map'|'knowledge-graph'|'aircraft'|'metrics'|'infographic'|'risk'|'table';
const families:VisualFamily[]=['architecture','topology','dashboard','timeline','decision-tree','heatmap','service-blueprint','journey-map','knowledge-graph','aircraft','metrics','infographic','risk','table'];
const modes:PublicationMode[]=['research','briefing','handbook','field-guide','technical-manual','playbook','decision-record','case-study'];
const hash=(value:string)=>[...value].reduce((sum,char,index)=>sum+char.charCodeAt(0)*(index+3),0);
function subjectFamilies(context:PublicationVisualContext):VisualFamily[]{const text=`${context.title} ${context.domain} ${context.tags.join(' ')}`.toLowerCase();if(context.ata.length)return['aircraft','topology','metrics','timeline','risk','table'];if(/telemetry|event|stream|edge|cloud|integration|observability/.test(text))return['topology','architecture','dashboard','timeline','heatmap','risk'];if(/reliability|defect|failure|predict|condition|health|trend/.test(text))return['metrics','heatmap','risk','timeline','aircraft','dashboard'];if(/planning|package|task|execution|workflow|control|dispatch/.test(text))return['timeline','service-blueprint','dashboard','decision-tree','journey-map','table'];if(/part|material|inventory|supply|rotable|aog/.test(text))return['heatmap','topology','dashboard','timeline','risk','table'];if(/knowledge|record|document|retrieval|nlp|lineage|configuration/.test(text))return['knowledge-graph','service-blueprint','table','timeline','architecture','infographic'];if(/ai|model|agent|copilot|vision|machine learning|generative/.test(text))return['decision-tree','knowledge-graph','risk','dashboard','infographic','architecture'];if(/security|cyber|trust|governance|assurance/.test(text))return['risk','architecture','decision-tree','heatmap','table','service-blueprint'];return families;}
export function visualSelection(context:PublicationVisualContext,role:VisualRole){const candidates=subjectFamilies(context);const roleIndex={hero:0,evidence:1,analysis:2,decision:3}[role];const seed=Number(context.issueDate.replaceAll('-',''));const family=candidates[(roleIndex+seed+hash(context.slug))%candidates.length];const variant=(['a','b','c'] as VisualVariant[])[(hash(`${context.title}:${role}:${context.issueDate}`)+seed+roleIndex)%3];return{family,variant};}
export function publicationMode(context:Pick<PublicationVisualContext,'slug'|'issueDate'>):PublicationMode{return modes[(hash(context.slug)+Number(context.issueDate.slice(5,7)))%modes.length];}
export const visualFamilies=families;
